"""Service layer and document merge engine for Enterprise Payroll Template Management System."""
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional
import uuid
import re

from sqlalchemy import select, update, delete
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.payroll_template import (
    PayrollTemplate,
    TemplateVersion,
    PayrollTemplateHistory,
    PayrollTemplateAuditLog,
)


class PayrollTemplateService:
    @staticmethod
    async def list_templates(db: AsyncSession, category_filter: Optional[str] = None) -> List[PayrollTemplate]:
        """Fetch all payroll document templates ordered by created_at."""
        stmt = select(PayrollTemplate)
        if category_filter and category_filter != "ALL":
            stmt = stmt.where(PayrollTemplate.category == category_filter.upper())
        stmt = stmt.order_by(PayrollTemplate.created_at.asc())

        res = await db.execute(stmt)
        templates = res.scalars().all()

        if not templates:
            # Seed Default Enterprise Payroll Templates
            defaults = [
                PayrollTemplate(
                    template_name="Modern Dark Sapphire Payslip",
                    template_code="TMPL_PAYSLIP_DARK",
                    category="PAYSLIP",
                    description="Default high-end dark themed PDF payslip template with brand header and salary breakdown grid",
                    doc_format="PDF",
                    language="EN",
                    status="PUBLISHED",
                    version_number=1,
                    is_default=True,
                    styling_theme="MODERN_DARK",
                    html_content=(
                        "<div style='font-family: sans-serif; background: #0d1526; color: #fff; p: 20px; border-radius: 12px;'>"
                        "<h1 style='color: #6366f1;'>{{company_name}} — Payslip</h1>"
                        "<p>Employee: <strong>{{employee_name}}</strong> ({{employee_id}})</p>"
                        "<p>Designation: {{designation}} | Dept: {{department}}</p>"
                        "<hr style='border-color: #334155;'/>"
                        "<table>"
                        "<tr><td>Basic Salary:</td><td>₹{{basic_salary}}</td></tr>"
                        "<tr><td>Gross Salary:</td><td>₹{{gross_salary}}</td></tr>"
                        "<tr><td>Net Salary Credited:</td><td><strong style='color: #10b981;'>₹{{net_salary}}</strong></td></tr>"
                        "</table>"
                        "<p>Bank: {{bank_name}} (A/C: {{account_number}})</p>"
                        "</div>"
                    ),
                    header_logo_url="https://aurix.ai/assets/logo.png",
                    footer_text="Confidential — Generated by Aurix AI Enterprise HRMS System"
                ),
                PayrollTemplate(
                    template_name="Enterprise Minimal White Payslip",
                    template_code="TMPL_PAYSLIP_CLEAN",
                    category="PAYSLIP",
                    description="Clean white light-mode PDF payslip template for standard printer output",
                    doc_format="PDF",
                    language="EN",
                    status="PUBLISHED",
                    version_number=1,
                    is_default=False,
                    styling_theme="ENTERPRISE_CLEAN",
                    html_content=(
                        "<div style='font-family: Arial; background: #ffffff; color: #1e293b; padding: 24px; border: 1px solid #cbd5e1;'>"
                        "<h2 style='color: #0f172a;'>PAYSLIP STATEMENT — {{company_name}}</h2>"
                        "<p>Name: {{employee_name}} | ID: {{employee_id}}</p>"
                        "<p>Designation: {{designation}}</p>"
                        "<table style='width: 100%; border-collapse: collapse;'>"
                        "<tr style='background: #f8fafc;'><td>Basic:</td><td>₹{{basic_salary}}</td></tr>"
                        "<tr><td>Net Payable:</td><td><strong>₹{{net_salary}}</strong></td></tr>"
                        "</table>"
                        "</div>"
                    ),
                    header_logo_url="https://aurix.ai/assets/logo-black.png",
                    footer_text="System Generated Statement"
                ),
                PayrollTemplate(
                    template_name="Annual Salary Revision Letter",
                    template_code="TMPL_SALARY_REVISION",
                    category="SALARY_REVISION",
                    description="Official company letterhead document for annual CTC increment and revision",
                    doc_format="PDF",
                    language="EN",
                    status="PUBLISHED",
                    version_number=1,
                    is_default=False,
                    styling_theme="CLASSIC_CORPORATE",
                    html_content=(
                        "<div style='font-family: Georgia, serif; padding: 30px; line-height: 1.6;'>"
                        "<h3>SALARY REVISION LETTER</h3>"
                        "<p>Dear <strong>{{employee_name}}</strong>,</p>"
                        "<p>We are pleased to inform you that effective April 1st, 2026, your gross revised CTC is updated to <strong>₹{{gross_salary}}</strong>.</p>"
                        "<p>Sincerely,<br/>Management Team<br/>{{company_name}}</p>"
                        "</div>"
                    ),
                    footer_text="Aurix AI HR Operations"
                ),
            ]

            for item in defaults:
                db.add(item)
            await db.commit()

            res = await db.execute(stmt)
            templates = res.scalars().all()

        return list(templates)

    @staticmethod
    async def get_template_by_id(db: AsyncSession, template_id: uuid.UUID) -> Optional[PayrollTemplate]:
        """Fetch single payroll template by ID."""
        stmt = select(PayrollTemplate).where(PayrollTemplate.id == template_id)
        res = await db.execute(stmt)
        return res.scalars().first()

    @staticmethod
    async def create_template(
        db: AsyncSession,
        data: Dict[str, Any],
        actor_email: Optional[str] = None,
        ip_address: Optional[str] = None,
        browser: Optional[str] = None
    ) -> PayrollTemplate:
        """Create new payroll template and log audit trail."""
        code = data.get("template_code", "").strip().upper()
        existing = await db.execute(select(PayrollTemplate).where(PayrollTemplate.template_code == code))
        if existing.scalars().first():
            raise ValueError(f"Template code '{code}' already exists")

        new_tmpl = PayrollTemplate(
            template_name=data.get("template_name", "New Document Template"),
            template_code=code,
            category=data.get("category", "PAYSLIP"),
            description=data.get("description", ""),
            doc_format=data.get("doc_format", "PDF"),
            language=data.get("language", "EN"),
            status="PUBLISHED",
            version_number=1,
            is_default=bool(data.get("is_default", False)),
            styling_theme=data.get("styling_theme", "MODERN_DARK"),
            html_content=data.get("html_content", "<div>Template Content</div>"),
            header_logo_url=data.get("header_logo_url"),
            footer_text=data.get("footer_text")
        )

        db.add(new_tmpl)
        await db.flush()

        audit_entry = PayrollTemplateAuditLog(
            template_id=new_tmpl.id,
            action="CREATED",
            actor=actor_email or "System Admin",
            previous_value=None,
            updated_value=new_tmpl.template_code,
            ip_address=ip_address or "127.0.0.1",
            browser=browser or "Dashboard Web",
            reason="Created document template"
        )
        db.add(audit_entry)

        await db.commit()
        await db.refresh(new_tmpl)
        return new_tmpl

    @staticmethod
    async def update_template(
        db: AsyncSession,
        template_id: uuid.UUID,
        payload: Dict[str, Any],
        actor_email: Optional[str] = None,
        ip_address: Optional[str] = None,
        browser: Optional[str] = None
    ) -> Optional[PayrollTemplate]:
        """Update template with automatic version increment if html_content changes."""
        tmpl = await PayrollTemplateService.get_template_by_id(db, template_id)
        if not tmpl:
            return None

        content_changed = "html_content" in payload and payload["html_content"] != tmpl.html_content

        if content_changed:
            # Save version snapshot
            v_snap = TemplateVersion(
                template_id=tmpl.id,
                version_number=tmpl.version_number,
                html_content=tmpl.html_content,
                changed_by=actor_email or "System Admin",
                reason="Updated HTML markup & styling"
            )
            db.add(v_snap)
            tmpl.version_number += 1

        for key, val in payload.items():
            if hasattr(tmpl, key) and val is not None:
                setattr(tmpl, key, val)

        tmpl.updated_at = datetime.utcnow()
        db.add(tmpl)

        audit_entry = PayrollTemplateAuditLog(
            template_id=tmpl.id,
            action="UPDATED",
            actor=actor_email or "System Admin",
            previous_value=f"v{tmpl.version_number - 1 if content_changed else tmpl.version_number}",
            updated_value=f"v{tmpl.version_number}",
            ip_address=ip_address or "127.0.0.1",
            browser=browser or "Dashboard Web",
            reason="Updated template settings & content"
        )
        db.add(audit_entry)

        await db.commit()
        await db.refresh(tmpl)
        return tmpl

    @staticmethod
    async def duplicate_template(db: AsyncSession, template_id: uuid.UUID) -> Optional[PayrollTemplate]:
        """Clone existing template into a new draft template."""
        tmpl = await PayrollTemplateService.get_template_by_id(db, template_id)
        if not tmpl:
            return None

        clone_code = f"{tmpl.template_code}_COPY_{uuid.uuid4().hex[:4].upper()}"
        clone = PayrollTemplate(
            template_name=f"{tmpl.template_name} (Copy)",
            template_code=clone_code,
            category=tmpl.category,
            description=f"Cloned copy of {tmpl.template_name}",
            doc_format=tmpl.doc_format,
            language=tmpl.language,
            status="DRAFT",
            version_number=1,
            is_default=False,
            styling_theme=tmpl.styling_theme,
            html_content=tmpl.html_content,
            header_logo_url=tmpl.header_logo_url,
            footer_text=tmpl.footer_text
        )

        db.add(clone)
        await db.commit()
        await db.refresh(clone)
        return clone

    @staticmethod
    async def render_merged_template(tmpl: PayrollTemplate, sample_data: Dict[str, Any]) -> str:
        """Substitute merge variables like {{employee_name}} into HTML markup."""
        merged = tmpl.html_content
        data = {
            "company_name": "Aurix AI Enterprise",
            "employee_name": "Ramesh Kumar",
            "employee_id": "EMP-1004",
            "designation": "Senior Software Engineer",
            "department": "Engineering",
            "basic_salary": "50,000",
            "gross_salary": "1,25,000",
            "net_salary": "1,08,500",
            "bank_name": "HDFC Bank",
            "account_number": "XXXXXXXX5819",
            **sample_data
        }

        for key, val in data.items():
            pattern = re.compile(r"\{\{\s*" + re.escape(key) + r"\s*\}\}", re.IGNORECASE)
            merged = pattern.sub(str(val), merged)

        return merged

    @staticmethod
    async def get_audit_logs(db: AsyncSession) -> List[Dict[str, Any]]:
        """Retrieve audit log entries for template operations."""
        stmt = select(PayrollTemplateAuditLog).order_by(PayrollTemplateAuditLog.created_at.desc()).limit(100)
        res = await db.execute(stmt)
        logs = res.scalars().all()
        return [
            {
                "id": str(l.id),
                "template_id": str(l.template_id) if l.template_id else None,
                "action": l.action,
                "actor": l.actor or "System Admin",
                "previous_value": l.previous_value or "None",
                "updated_value": l.updated_value or "Updated",
                "ip_address": l.ip_address or "127.0.0.1",
                "browser": l.browser or "Dashboard Web",
                "reason": l.reason or "Document template action",
                "timestamp": l.created_at.isoformat() if l.created_at else ""
            }
            for l in logs
        ]
