[pytest]
testpaths = tests
asyncio_mode = strict
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning
    ignore::pydantic.PydanticDeprecatedSince20
    ignore::pydantic.warnings.UnsupportedFieldAttributeWarning
