"""create_exit_tables

Revision ID: 05b1e1215226
Revises: a8252eecb5b4
Create Date: 2026-06-27 13:12:19.153634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b1e1215226'
down_revision: Union[str, None] = 'a8252eecb5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_exits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('last_working_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=False),
    sa.Column('personal_phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'SUBMITTED'"), nullable=False),
    sa.Column('manager_remarks', sa.Text(), nullable=True),
    sa.Column('hr_remarks', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_exits_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_exits'))
    )
    op.create_index('ix_employee_exits_employee_id', 'employee_exits', ['employee_id'], unique=False)
    op.create_index('ix_employee_exits_is_deleted', 'employee_exits', ['is_deleted'], unique=False)
    op.create_index('ix_employee_exits_status', 'employee_exits', ['status'], unique=False)
    op.create_table('asset_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exit_id', sa.UUID(), nullable=False),
    sa.Column('asset_name', sa.String(length=100), nullable=False),
    sa.Column('return_status', sa.String(length=20), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('hr_remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exit_id'], ['employee_exits.id'], name=op.f('fk_asset_returns_exit_id_employee_exits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_returns'))
    )
    op.create_table('clearance_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exit_id', sa.UUID(), nullable=False),
    sa.Column('it_clearance', sa.Boolean(), nullable=False),
    sa.Column('hr_clearance', sa.Boolean(), nullable=False),
    sa.Column('finance_clearance', sa.Boolean(), nullable=False),
    sa.Column('admin_clearance', sa.Boolean(), nullable=False),
    sa.Column('manager_clearance', sa.Boolean(), nullable=False),
    sa.Column('security_clearance', sa.Boolean(), nullable=False),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['exit_id'], ['employee_exits.id'], name=op.f('fk_clearance_requests_exit_id_employee_exits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clearance_requests'))
    )
    op.create_table('exit_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exit_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exit_id'], ['employee_exits.id'], name=op.f('fk_exit_documents_exit_id_employee_exits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_documents'))
    )
    op.create_table('exit_interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exit_id', sa.UUID(), nullable=False),
    sa.Column('interview_date', sa.Date(), nullable=False),
    sa.Column('interviewer_name', sa.String(length=100), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('reason_for_leaving', sa.Text(), nullable=False),
    sa.Column('would_rejoin', sa.Boolean(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exit_id'], ['employee_exits.id'], name=op.f('fk_exit_interviews_exit_id_employee_exits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_interviews'))
    )
    op.create_table('fnf_settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exit_id', sa.UUID(), nullable=False),
    sa.Column('last_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pending_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('leave_encashment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('incentives', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recoveries', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notice_recovery', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('asset_recovery', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('loan_recovery', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_payable_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['exit_id'], ['employee_exits.id'], name=op.f('fk_fnf_settlements_exit_id_employee_exits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fnf_settlements'))
    )
    op.create_table('knowledge_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exit_id', sa.UUID(), nullable=False),
    sa.Column('projects_handed_over', sa.Text(), nullable=False),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('replacement_assigned_id', sa.UUID(), nullable=True),
    sa.Column('manager_remarks', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['exit_id'], ['employee_exits.id'], name=op.f('fk_knowledge_transfers_exit_id_employee_exits'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replacement_assigned_id'], ['employees.id'], name=op.f('fk_knowledge_transfers_replacement_assigned_id_employees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_transfers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_transfers')
    op.drop_table('fnf_settlements')
    op.drop_table('exit_interviews')
    op.drop_table('exit_documents')
    op.drop_table('clearance_requests')
    op.drop_table('asset_returns')
    op.drop_index('ix_employee_exits_status', table_name='employee_exits')
    op.drop_index('ix_employee_exits_is_deleted', table_name='employee_exits')
    op.drop_index('ix_employee_exits_employee_id', table_name='employee_exits')
    op.drop_table('employee_exits')
    # ### end Alembic commands ###
