"""create daily attendance table

Revision ID: 0e8b0155cc94
Revises: 4bb92df30546
Create Date: 2026-07-14 15:20:19.291454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8b0155cc94'
down_revision: Union[str, None] = '4bb92df30546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('face_image_url', sa.String(length=500), nullable=True),
    sa.Column('checkout_image_url', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('working_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_attendances_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendances_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendances')),
    sa.UniqueConstraint('employee_id', 'date', name='uq_employee_date_attendance')
    )
    op.create_index('ix_attendances_company_id', 'attendances', ['company_id'], unique=False)
    op.create_index('ix_attendances_date', 'attendances', ['date'], unique=False)
    op.create_index('ix_attendances_employee_id', 'attendances', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendances_employee_id', table_name='attendances')
    op.drop_index('ix_attendances_date', table_name='attendances')
    op.drop_index('ix_attendances_company_id', table_name='attendances')
    op.drop_table('attendances')
    # ### end Alembic commands ###
