"""create_department_tables

Revision ID: 12d18dd1f4b6
Revises: a3526c6fd7bd
Create Date: 2026-06-27 12:51:02.480111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d18dd1f4b6'
down_revision: Union[str, None] = 'a3526c6fd7bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_code', sa.String(length=30), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('parent_department_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('cost_center', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_departments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_departments_manager_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.id'], name=op.f('fk_departments_parent_department_id_departments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index('ix_departments_department_code', 'departments', ['department_code'], unique=True)
    op.create_index('ix_departments_department_name', 'departments', ['department_name'], unique=True)
    op.create_index('ix_departments_is_deleted', 'departments', ['is_deleted'], unique=False)
    op.create_index('ix_departments_manager_id', 'departments', ['manager_id'], unique=False)
    op.create_index('ix_departments_parent_department_id', 'departments', ['parent_department_id'], unique=False)
    op.create_index('ix_departments_status', 'departments', ['status'], unique=False)
    op.add_column('employees', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_employees_department_id_departments'), 'employees', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.add_column('managers', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_managers_department_id_departments'), 'managers', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_managers_department_id_departments'), 'managers', type_='foreignkey')
    op.drop_column('managers', 'department_id')
    op.drop_constraint(op.f('fk_employees_department_id_departments'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'department_id')
    op.drop_index('ix_departments_status', table_name='departments')
    op.drop_index('ix_departments_parent_department_id', table_name='departments')
    op.drop_index('ix_departments_manager_id', table_name='departments')
    op.drop_index('ix_departments_is_deleted', table_name='departments')
    op.drop_index('ix_departments_department_name', table_name='departments')
    op.drop_index('ix_departments_department_code', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
