"""create_document_tables

Revision ID: 1b4d76212374
Revises: 8a0d318bd726
Create Date: 2026-06-27 13:31:14.748016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4d76212374'
down_revision: Union[str, None] = '8a0d318bd726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_company', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_document_categories_code'))
    )
    op.create_table('company_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('visibility', sa.String(length=30), server_default=sa.text("'PUBLIC'"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PUBLISHED'"), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['document_categories.id'], name=op.f('fk_company_documents_category_id_document_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_company_documents_uploaded_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_documents'))
    )
    op.create_index('ix_company_documents_category_id', 'company_documents', ['category_id'], unique=False)
    op.create_index('ix_company_documents_is_deleted', 'company_documents', ['is_deleted'], unique=False)
    op.create_table('document_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_document_audit_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_audit_logs'))
    )
    op.create_table('document_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_document_templates_created_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_templates')),
    sa.UniqueConstraint('name', name=op.f('uq_document_templates_name'))
    )
    op.create_table('document_expiry_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_doc_id', sa.UUID(), nullable=False),
    sa.Column('days_remaining', sa.Integer(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_doc_id'], ['employee_documents.id'], name=op.f('fk_document_expiry_tracking_employee_doc_id_employee_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_expiry_tracking'))
    )
    op.create_table('document_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_doc_id', sa.UUID(), nullable=False),
    sa.Column('signer_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['employee_doc_id'], ['employee_documents.id'], name=op.f('fk_document_signatures_employee_doc_id_employee_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signer_user_id'], ['users.id'], name=op.f('fk_document_signatures_signer_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_signatures'))
    )
    op.create_table('document_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_doc_id', sa.UUID(), nullable=False),
    sa.Column('verifier_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_doc_id'], ['employee_documents.id'], name=op.f('fk_document_verifications_employee_doc_id_employee_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verifier_user_id'], ['users.id'], name=op.f('fk_document_verifications_verifier_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_verifications'))
    )
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_doc_id', sa.UUID(), nullable=True),
    sa.Column('company_doc_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_doc_id'], ['company_documents.id'], name=op.f('fk_document_versions_company_doc_id_company_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_doc_id'], ['employee_documents.id'], name=op.f('fk_document_versions_employee_doc_id_employee_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_document_versions_uploaded_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions'))
    )
    op.add_column('employee_documents', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('employee_documents', sa.Column('uploaded_by', sa.UUID(), nullable=True))
    op.add_column('employee_documents', sa.Column('title', sa.String(length=150), nullable=True))
    op.add_column('employee_documents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('employee_documents', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('employee_documents', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('employee_documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('employee_documents', sa.Column('issue_date', sa.Date(), nullable=True))
    op.add_column('employee_documents', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('employee_documents', sa.Column('status', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False))
    op.add_column('employee_documents', sa.Column('visibility', sa.String(length=30), server_default=sa.text("'PRIVATE'"), nullable=False))
    op.add_column('employee_documents', sa.Column('tags', sa.String(length=255), nullable=True))
    op.add_column('employee_documents', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('employee_documents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('employee_documents', 'document_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('employee_documents', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index('ix_employee_documents_is_deleted', 'employee_documents', ['is_deleted'], unique=False)
    op.create_index('ix_employee_documents_status', 'employee_documents', ['status'], unique=False)
    op.create_foreign_key(op.f('fk_employee_documents_uploaded_by_users'), 'employee_documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_employee_documents_category_id_document_categories'), 'employee_documents', 'document_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_employee_documents_category_id_document_categories'), 'employee_documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_employee_documents_uploaded_by_users'), 'employee_documents', type_='foreignkey')
    op.drop_index('ix_employee_documents_status', table_name='employee_documents')
    op.drop_index('ix_employee_documents_is_deleted', table_name='employee_documents')
    op.alter_column('employee_documents', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('employee_documents', 'document_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('employee_documents', 'deleted_at')
    op.drop_column('employee_documents', 'is_deleted')
    op.drop_column('employee_documents', 'tags')
    op.drop_column('employee_documents', 'visibility')
    op.drop_column('employee_documents', 'status')
    op.drop_column('employee_documents', 'version')
    op.drop_column('employee_documents', 'issue_date')
    op.drop_column('employee_documents', 'file_size')
    op.drop_column('employee_documents', 'file_name')
    op.drop_column('employee_documents', 'file_path')
    op.drop_column('employee_documents', 'description')
    op.drop_column('employee_documents', 'title')
    op.drop_column('employee_documents', 'uploaded_by')
    op.drop_column('employee_documents', 'category_id')
    op.drop_table('document_versions')
    op.drop_table('document_verifications')
    op.drop_table('document_signatures')
    op.drop_table('document_expiry_tracking')
    op.drop_table('document_templates')
    op.drop_table('document_audit_logs')
    op.drop_index('ix_company_documents_is_deleted', table_name='company_documents')
    op.drop_index('ix_company_documents_category_id', table_name='company_documents')
    op.drop_table('company_documents')
    op.drop_table('document_categories')
    # ### end Alembic commands ###
