"""add_extension_number_to_departments

Revision ID: 1dc109f7a733
Revises: c70e966a30a7
Create Date: 2026-07-18 11:17:12.506520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc109f7a733'
down_revision: Union[str, None] = 'c70e966a30a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('extension_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'extension_number')
    # ### end Alembic commands ###
