"""add account holder name to bank accounts

Revision ID: 3ed50d119ecc
Revises: 0e8b0155cc94
Create Date: 2026-07-14 15:46:28.272652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed50d119ecc'
down_revision: Union[str, None] = '0e8b0155cc94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_bank_accounts', sa.Column('account_holder_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_bank_accounts', 'account_holder_name')
    # ### end Alembic commands ###
