"""create_employee_tables

Revision ID: 48c3c6bee28c
Revises: 7f7dfc97b136
Create Date: 2026-06-27 12:39:00.364283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c3c6bee28c'
down_revision: Union[str, None] = '7f7dfc97b136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=False),
    sa.Column('company_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('alternate_phone', sa.String(length=15), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('reporting_manager_id', sa.UUID(), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('work_location', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=30), server_default=sa.text("'FULL_TIME'"), nullable=False),
    sa.Column('employment_status', sa.String(length=30), server_default=sa.text("'PROBATION'"), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('probation_end_date', sa.Date(), nullable=True),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('ctc', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('hra', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('bonus', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pf', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('esi', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('professional_tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('role', sa.String(length=50), server_default=sa.text("'employee'"), nullable=False),
    sa.Column('leave_group', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('activation_token', sa.String(length=128), nullable=True),
    sa.Column('activation_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_employees_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.id'], name=op.f('fk_employees_reporting_manager_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employees_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_index('ix_employees_company_email', 'employees', ['company_email'], unique=False)
    op.create_index('ix_employees_department', 'employees', ['department'], unique=False)
    op.create_index('ix_employees_employee_id', 'employees', ['employee_id'], unique=True)
    op.create_index('ix_employees_is_deleted', 'employees', ['is_deleted'], unique=False)
    op.create_index('ix_employees_personal_email', 'employees', ['personal_email'], unique=True)
    op.create_index('ix_employees_status', 'employees', ['status'], unique=False)
    op.create_index('ix_employees_user_id', 'employees', ['user_id'], unique=False)
    op.create_table('employee_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), server_default=sa.text("'India'"), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('is_same_as_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_addresses_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_addresses'))
    )
    op.create_index('ix_employee_addresses_employee_id', 'employee_addresses', ['employee_id'], unique=False)
    op.create_table('employee_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('asset_name', sa.String(length=150), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=True),
    sa.Column('asset_code', sa.String(length=50), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_assets_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_assets'))
    )
    op.create_index('ix_employee_assets_employee_id', 'employee_assets', ['employee_id'], unique=False)
    op.create_table('employee_bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('ifsc_code', sa.String(length=15), nullable=False),
    sa.Column('account_type', sa.String(length=20), server_default=sa.text("'SAVINGS'"), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_bank_accounts_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_bank_accounts'))
    )
    op.create_index('ix_employee_bank_accounts_employee_id', 'employee_bank_accounts', ['employee_id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_documents_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_employee_documents_verified_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_documents'))
    )
    op.create_index('ix_employee_documents_employee_id', 'employee_documents', ['employee_id'], unique=False)
    op.create_table('employee_education',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('degree', sa.String(length=150), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('field_of_study', sa.String(length=150), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_education_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_education'))
    )
    op.create_index('ix_employee_education_employee_id', 'employee_education', ['employee_id'], unique=False)
    op.create_table('employee_emergency_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('alternate_phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_emergency_contacts_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_emergency_contacts'))
    )
    op.create_index('ix_employee_emergency_contacts_employee_id', 'employee_emergency_contacts', ['employee_id'], unique=False)
    op.create_table('employee_experience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=False),
    sa.Column('employment_type', sa.String(length=30), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_experience_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_experience'))
    )
    op.create_index('ix_employee_experience_employee_id', 'employee_experience', ['employee_id'], unique=False)
    op.create_table('employee_leave_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=6, scale=1), server_default=sa.text('0'), nullable=False),
    sa.Column('carry_forward', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_leave_policies_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_leave_policies'))
    )
    op.create_index('ix_employee_leave_policies_employee_id', 'employee_leave_policies', ['employee_id'], unique=False)
    op.create_table('employee_onboarding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_onboarding_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_employee_onboarding_verified_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_onboarding'))
    )
    op.create_index('ix_employee_onboarding_employee_id', 'employee_onboarding', ['employee_id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('proficiency', sa.String(length=20), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_skills_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_skills'))
    )
    op.create_index('ix_employee_skills_employee_id', 'employee_skills', ['employee_id'], unique=False)
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    op.drop_index('ix_employee_skills_employee_id', table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index('ix_employee_onboarding_employee_id', table_name='employee_onboarding')
    op.drop_table('employee_onboarding')
    op.drop_index('ix_employee_leave_policies_employee_id', table_name='employee_leave_policies')
    op.drop_table('employee_leave_policies')
    op.drop_index('ix_employee_experience_employee_id', table_name='employee_experience')
    op.drop_table('employee_experience')
    op.drop_index('ix_employee_emergency_contacts_employee_id', table_name='employee_emergency_contacts')
    op.drop_table('employee_emergency_contacts')
    op.drop_index('ix_employee_education_employee_id', table_name='employee_education')
    op.drop_table('employee_education')
    op.drop_index('ix_employee_documents_employee_id', table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index('ix_employee_bank_accounts_employee_id', table_name='employee_bank_accounts')
    op.drop_table('employee_bank_accounts')
    op.drop_index('ix_employee_assets_employee_id', table_name='employee_assets')
    op.drop_table('employee_assets')
    op.drop_index('ix_employee_addresses_employee_id', table_name='employee_addresses')
    op.drop_table('employee_addresses')
    op.drop_index('ix_employees_user_id', table_name='employees')
    op.drop_index('ix_employees_status', table_name='employees')
    op.drop_index('ix_employees_personal_email', table_name='employees')
    op.drop_index('ix_employees_is_deleted', table_name='employees')
    op.drop_index('ix_employees_employee_id', table_name='employees')
    op.drop_index('ix_employees_department', table_name='employees')
    op.drop_index('ix_employees_company_email', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
