"""add_payroll_new_models

Revision ID: 4bb92df30546
Revises: cc669a8976df
Create Date: 2026-07-14 14:06:48.615358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bb92df30546'
down_revision: Union[str, None] = 'cc669a8976df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_email_purpose_created_at'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_purpose'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.alter_column('ai_compensation_recommendations', 'recommended_bonus',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_compensation_recommendations', 'recommended_incentives',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_compensation_recommendations', 'recommended_retention_bonus',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_compensation_recommendations', 'recommended_stock_options',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_compensation_recommendations', 'recommended_increment_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_compensation_recommendations', 'market_ratio',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_compensation_recommendations', 'equity_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('compliance_audit_logs', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('emotion_aware_chat_messages', 'detected_emotion',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('employee_risk_assessments', 'overall_risk_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('generated_email_logs', 'tone',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('generated_goals', 'scope',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.alter_column('generated_goals', 'current_value',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_compensation_benchmarks', 'region',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=False)
    op.alter_column('onboarding_progress', 'current_step',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('wellness_anonymous_chat_messages', 'sentiment_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wellness_escalation_rules', 'min_mood_score',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wellness_escalation_rules', 'stress_trigger_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('wellness_escalation_rules', 'action_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wellness_escalation_rules', 'action_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'ALERT_HR'::character varying"),
               existing_nullable=False)
    op.alter_column('wellness_escalation_rules', 'stress_trigger_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'HIGH'::character varying"),
               existing_nullable=False)
    op.alter_column('wellness_escalation_rules', 'min_mood_score',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('wellness_anonymous_chat_messages', 'sentiment_score',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    op.alter_column('onboarding_progress', 'current_step',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_compensation_benchmarks', 'region',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'Global'::character varying"),
               existing_nullable=False)
    op.alter_column('generated_goals', 'current_value',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'0'::character varying"),
               existing_nullable=False)
    op.alter_column('generated_goals', 'scope',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'INDIVIDUAL'::character varying"),
               existing_nullable=False)
    op.alter_column('generated_email_logs', 'tone',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'PROFESSIONAL'::character varying"),
               existing_nullable=False)
    op.alter_column('employee_risk_assessments', 'overall_risk_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'LOW'::character varying"),
               existing_nullable=False)
    op.alter_column('emotion_aware_chat_messages', 'detected_emotion',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'NEUTRAL'::character varying"),
               existing_nullable=False)
    op.alter_column('compliance_audit_logs', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'LOW'::character varying"),
               existing_nullable=False)
    op.alter_column('ai_compensation_recommendations', 'equity_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'COMPLIANT'::character varying"),
               existing_nullable=False)
    op.alter_column('ai_compensation_recommendations', 'market_ratio',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=sa.text('1.00'),
               existing_nullable=False)
    op.alter_column('ai_compensation_recommendations', 'recommended_increment_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    op.alter_column('ai_compensation_recommendations', 'recommended_stock_options',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('ai_compensation_recommendations', 'recommended_retention_bonus',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    op.alter_column('ai_compensation_recommendations', 'recommended_incentives',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    op.alter_column('ai_compensation_recommendations', 'recommended_bonus',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False)
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('code_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('consumed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('otp_codes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_codes_pkey'))
    )
    op.create_index(op.f('ix_otp_codes_purpose'), 'otp_codes', ['purpose'], unique=False)
    op.create_index(op.f('ix_otp_codes_email_purpose_created_at'), 'otp_codes', ['email', 'purpose', 'created_at'], unique=False)
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=False)
    # ### end Alembic commands ###
