"""add_company_and_multitenancy

Revision ID: 614ffa57eedf
Revises: f433d8a18647
Create Date: 2026-07-02 16:03:12.923979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614ffa57eedf'
down_revision: Union[str, None] = 'f433d8a18647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('company_profile', sa.JSON(), nullable=True),
    sa.Column('hr_settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_table('company_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=True),
    sa.Column('time_format', sa.String(length=20), nullable=True),
    sa.Column('financial_year', sa.String(length=20), nullable=True),
    sa.Column('week_start_day', sa.String(length=20), nullable=True),
    sa.Column('working_days', sa.JSON(), nullable=True),
    sa.Column('office_timing', sa.String(length=50), nullable=True),
    sa.Column('default_shift', sa.String(length=50), nullable=True),
    sa.Column('leave_policy_template', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_settings_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_settings'))
    )
    op.create_table('designations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_designations_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_designations'))
    )
    op.create_table('leave_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('days_allowed', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_leave_policies_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_policies'))
    )
    op.create_table('onboarding_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_onboarding_progress_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_progress')),
    sa.UniqueConstraint('company_id', name=op.f('uq_onboarding_progress_company_id'))
    )
    op.create_table('shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=False),
    sa.Column('end_time', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_shifts_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )
    op.add_column('announcements', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_announcements_company_id_companies'), 'announcements', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('applications', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_applications_company_id_companies'), 'applications', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('calendar_events', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_calendar_events_company_id_companies'), 'calendar_events', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('company_documents', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_company_documents_company_id_companies'), 'company_documents', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('company_events', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_company_events_company_id_companies'), 'company_events', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('company_news', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_company_news_company_id_companies'), 'company_news', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('departments', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_departments_company_id_companies'), 'departments', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('employee_exits', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_employee_exits_company_id_companies'), 'employee_exits', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('employees', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_employees_company_id_companies'), 'employees', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('interviews', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_interviews_company_id_companies'), 'interviews', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('jobs', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_jobs_company_id_companies'), 'jobs', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('managers', sa.Column('company_id', sa.UUID(), nullable=True))
    op.add_column('managers', sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('managers', sa.Column('invited_by', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_managers_company_id_companies'), 'managers', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_managers_invited_by_users'), 'managers', 'users', ['invited_by'], ['id'], ondelete='SET NULL')
    op.add_column('meetings', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_meetings_company_id_companies'), 'meetings', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('offers', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_offers_company_id_companies'), 'offers', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('polls', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_polls_company_id_companies'), 'polls', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('company_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('first_login', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('onboarding_step', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.create_foreign_key(op.f('fk_users_company_id_companies'), 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_company_id_companies'), 'users', type_='foreignkey')
    op.drop_column('users', 'onboarding_step')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'first_login')
    op.drop_column('users', 'is_super_admin')
    op.drop_column('users', 'company_id')
    op.drop_constraint(op.f('fk_polls_company_id_companies'), 'polls', type_='foreignkey')
    op.drop_column('polls', 'company_id')
    op.drop_constraint(op.f('fk_offers_company_id_companies'), 'offers', type_='foreignkey')
    op.drop_column('offers', 'company_id')
    op.drop_constraint(op.f('fk_meetings_company_id_companies'), 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'company_id')
    op.drop_constraint(op.f('fk_managers_invited_by_users'), 'managers', type_='foreignkey')
    op.drop_constraint(op.f('fk_managers_company_id_companies'), 'managers', type_='foreignkey')
    op.drop_column('managers', 'invited_by')
    op.drop_column('managers', 'invited_at')
    op.drop_column('managers', 'company_id')
    op.drop_constraint(op.f('fk_jobs_company_id_companies'), 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'company_id')
    op.drop_constraint(op.f('fk_interviews_company_id_companies'), 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'company_id')
    op.drop_constraint(op.f('fk_employees_company_id_companies'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'company_id')
    op.drop_constraint(op.f('fk_employee_exits_company_id_companies'), 'employee_exits', type_='foreignkey')
    op.drop_column('employee_exits', 'company_id')
    op.drop_constraint(op.f('fk_departments_company_id_companies'), 'departments', type_='foreignkey')
    op.drop_column('departments', 'company_id')
    op.drop_constraint(op.f('fk_company_news_company_id_companies'), 'company_news', type_='foreignkey')
    op.drop_column('company_news', 'company_id')
    op.drop_constraint(op.f('fk_company_events_company_id_companies'), 'company_events', type_='foreignkey')
    op.drop_column('company_events', 'company_id')
    op.drop_constraint(op.f('fk_company_documents_company_id_companies'), 'company_documents', type_='foreignkey')
    op.drop_column('company_documents', 'company_id')
    op.drop_constraint(op.f('fk_calendar_events_company_id_companies'), 'calendar_events', type_='foreignkey')
    op.drop_column('calendar_events', 'company_id')
    op.drop_constraint(op.f('fk_applications_company_id_companies'), 'applications', type_='foreignkey')
    op.drop_column('applications', 'company_id')
    op.drop_constraint(op.f('fk_announcements_company_id_companies'), 'announcements', type_='foreignkey')
    op.drop_column('announcements', 'company_id')
    op.drop_table('shifts')
    op.drop_table('onboarding_progress')
    op.drop_table('leave_policies')
    op.drop_table('designations')
    op.drop_table('company_settings')
    op.drop_table('companies')
    # ### end Alembic commands ###
