"""add_pending_email_to_users

Revision ID: 7f7dfc97b136
Revises: 0bef3579f5e2
Create Date: 2026-06-27 12:07:46.540262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f7dfc97b136'
down_revision: Union[str, None] = '0bef3579f5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_email')
    # ### end Alembic commands ###
