"""create_manager_tables

Revision ID: a3526c6fd7bd
Revises: 48c3c6bee28c
Create Date: 2026-06-27 12:45:39.622397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3526c6fd7bd'
down_revision: Union[str, None] = '48c3c6bee28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('manager_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=False),
    sa.Column('company_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('alternate_phone', sa.String(length=15), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('work_location', sa.String(length=100), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('employment_type', sa.String(length=30), server_default=sa.text("'FULL_TIME'"), nullable=False),
    sa.Column('employment_status', sa.String(length=30), server_default=sa.text("'PROBATION'"), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('probation_period_months', sa.Integer(), nullable=True),
    sa.Column('ctc', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('hra', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('bonus', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pf', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('esi', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('professional_tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('role', sa.String(length=50), server_default=sa.text("'manager'"), nullable=False),
    sa.Column('leave_group', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('activation_token', sa.String(length=128), nullable=True),
    sa.Column('activation_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_managers_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_managers_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_managers'))
    )
    op.create_index('ix_managers_company_email', 'managers', ['company_email'], unique=False)
    op.create_index('ix_managers_department', 'managers', ['department'], unique=False)
    op.create_index('ix_managers_is_deleted', 'managers', ['is_deleted'], unique=False)
    op.create_index('ix_managers_manager_id', 'managers', ['manager_id'], unique=True)
    op.create_index('ix_managers_personal_email', 'managers', ['personal_email'], unique=True)
    op.create_index('ix_managers_status', 'managers', ['status'], unique=False)
    op.create_index('ix_managers_user_id', 'managers', ['user_id'], unique=False)
    op.create_table('manager_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), server_default=sa.text("'India'"), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('is_same_as_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], name=op.f('fk_manager_addresses_manager_id_managers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_addresses'))
    )
    op.create_index('ix_manager_addresses_manager_id', 'manager_addresses', ['manager_id'], unique=False)
    op.create_table('manager_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], name=op.f('fk_manager_documents_manager_id_managers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_documents'))
    )
    op.create_index('ix_manager_documents_manager_id', 'manager_documents', ['manager_id'], unique=False)
    op.create_table('manager_education',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('degree', sa.String(length=150), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('field_of_study', sa.String(length=150), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], name=op.f('fk_manager_education_manager_id_managers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_education'))
    )
    op.create_index('ix_manager_education_manager_id', 'manager_education', ['manager_id'], unique=False)
    op.create_table('manager_emergency_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('alternate_phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], name=op.f('fk_manager_emergency_contacts_manager_id_managers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_emergency_contacts'))
    )
    op.create_index('ix_manager_emergency_contacts_manager_id', 'manager_emergency_contacts', ['manager_id'], unique=False)
    op.create_table('manager_experience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=False),
    sa.Column('employment_type', sa.String(length=30), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], name=op.f('fk_manager_experience_manager_id_managers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_experience'))
    )
    op.create_index('ix_manager_experience_manager_id', 'manager_experience', ['manager_id'], unique=False)
    op.create_table('manager_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('proficiency', sa.String(length=20), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], name=op.f('fk_manager_skills_manager_id_managers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_skills'))
    )
    op.create_index('ix_manager_skills_manager_id', 'manager_skills', ['manager_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_manager_skills_manager_id', table_name='manager_skills')
    op.drop_table('manager_skills')
    op.drop_index('ix_manager_experience_manager_id', table_name='manager_experience')
    op.drop_table('manager_experience')
    op.drop_index('ix_manager_emergency_contacts_manager_id', table_name='manager_emergency_contacts')
    op.drop_table('manager_emergency_contacts')
    op.drop_index('ix_manager_education_manager_id', table_name='manager_education')
    op.drop_table('manager_education')
    op.drop_index('ix_manager_documents_manager_id', table_name='manager_documents')
    op.drop_table('manager_documents')
    op.drop_index('ix_manager_addresses_manager_id', table_name='manager_addresses')
    op.drop_table('manager_addresses')
    op.drop_index('ix_managers_user_id', table_name='managers')
    op.drop_index('ix_managers_status', table_name='managers')
    op.drop_index('ix_managers_personal_email', table_name='managers')
    op.drop_index('ix_managers_manager_id', table_name='managers')
    op.drop_index('ix_managers_is_deleted', table_name='managers')
    op.drop_index('ix_managers_department', table_name='managers')
    op.drop_index('ix_managers_company_email', table_name='managers')
    op.drop_table('managers')
    # ### end Alembic commands ###
