"""create_recruitment_tables

Revision ID: a8252eecb5b4
Revises: 12d18dd1f4b6
Create Date: 2026-06-27 13:05:48.738622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8252eecb5b4'
down_revision: Union[str, None] = '12d18dd1f4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_page_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=100), server_default=sa.text("'Aurix'"), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('theme_color', sa.String(length=20), server_default=sa.text("'#0f172a'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_page_settings'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('employment_type', sa.String(length=30), server_default=sa.text("'FULL_TIME'"), nullable=False),
    sa.Column('experience_required', sa.String(length=100), nullable=True),
    sa.Column('min_experience', sa.Integer(), nullable=False),
    sa.Column('max_experience', sa.Integer(), nullable=True),
    sa.Column('min_salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('interview_process_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_jobs_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_is_deleted', 'jobs', ['is_deleted'], unique=False)
    op.create_index('ix_jobs_slug', 'jobs', ['slug'], unique=True)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('current_company', sa.String(length=150), nullable=True),
    sa.Column('current_designation', sa.String(length=150), nullable=True),
    sa.Column('current_ctc', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_ctc', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notice_period', sa.String(length=50), nullable=True),
    sa.Column('highest_qualification', sa.String(length=150), nullable=True),
    sa.Column('experience_years', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('declaration_checked', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'APPLIED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_applications_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index('ix_applications_email', 'applications', ['email'], unique=False)
    op.create_index('ix_applications_job_id', 'applications', ['job_id'], unique=False)
    op.create_index('ix_applications_status', 'applications', ['status'], unique=False)
    op.create_table('job_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_skills_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_skills'))
    )
    op.create_table('application_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=30), server_default=sa.text("'RESUME'"), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_documents_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_documents'))
    )
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'SCHEDULED'"), nullable=False),
    sa.Column('current_round_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_interviews_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviews'))
    )
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('ctc', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('offer_expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'SENT'"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_offers_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_offers_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    op.create_table('interview_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('round_name', sa.String(length=100), nullable=False),
    sa.Column('round_order', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('interviewer_name', sa.String(length=100), nullable=True),
    sa.Column('conducted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_interview_rounds_interview_id_interviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_rounds'))
    )
    op.create_table('offer_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_offer_documents_offer_id_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_documents'))
    )
    op.create_table('interview_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('interview_date', sa.Date(), nullable=False),
    sa.Column('interview_time', sa.Time(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('office_address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_interview_schedules_interview_id_interviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['interview_rounds.id'], name=op.f('fk_interview_schedules_round_id_interview_rounds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_schedules'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_schedules')
    op.drop_table('offer_documents')
    op.drop_table('interview_rounds')
    op.drop_table('offers')
    op.drop_table('interviews')
    op.drop_table('application_documents')
    op.drop_table('job_skills')
    op.drop_index('ix_applications_status', table_name='applications')
    op.drop_index('ix_applications_job_id', table_name='applications')
    op.drop_index('ix_applications_email', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_slug', table_name='jobs')
    op.drop_index('ix_jobs_is_deleted', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('career_page_settings')
    # ### end Alembic commands ###
