"""create_ai_copilot_tables

Revision ID: bd443a5583cc
Revises: 1a7b13ed1dcd
Create Date: 2026-06-27 13:58:43.834180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd443a5583cc'
down_revision: Union[str, None] = '1a7b13ed1dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('prompt_length', sa.Integer(), nullable=False),
    sa.Column('response_length', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_logs'))
    )
    op.create_table('job_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_embeddings_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_embeddings'))
    )
    op.create_table('resume_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_resume_documents_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_documents'))
    )
    op.create_table('candidate_ai_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_document_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('professional_summary', sa.Text(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('hiring_recommendation', sa.String(length=50), nullable=False),
    sa.Column('culture_fit', sa.Text(), nullable=True),
    sa.Column('technical_fit', sa.Text(), nullable=True),
    sa.Column('communication_assessment', sa.Text(), nullable=True),
    sa.Column('career_progression', sa.Text(), nullable=True),
    sa.Column('skill_gaps', sa.JSON(), nullable=False),
    sa.Column('upskilling_suggestions', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_candidate_ai_analysis_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_document_id'], ['resume_documents.id'], name=op.f('fk_candidate_ai_analysis_resume_document_id_resume_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_ai_analysis'))
    )
    op.create_table('candidate_rankings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_document_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('technical_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('experience_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('education_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('project_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('certification_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('communication_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('leadership_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('culture_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('learning_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_candidate_rankings_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_document_id'], ['resume_documents.id'], name=op.f('fk_candidate_rankings_resume_document_id_resume_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_rankings'))
    )
    op.create_table('candidate_similarity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_document_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('matching_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_candidate_similarity_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_document_id'], ['resume_documents.id'], name=op.f('fk_candidate_similarity_resume_document_id_resume_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_similarity'))
    )
    op.create_table('interview_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_document_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_interview_questions_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_document_id'], ['resume_documents.id'], name=op.f('fk_interview_questions_resume_document_id_resume_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_questions'))
    )
    op.create_table('resume_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_document_id', sa.UUID(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_document_id'], ['resume_documents.id'], name=op.f('fk_resume_embeddings_resume_document_id_resume_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_embeddings'))
    )
    op.create_table('resume_extracted_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_document_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True),
    sa.Column('github_url', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experience', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_document_id'], ['resume_documents.id'], name=op.f('fk_resume_extracted_data_resume_document_id_resume_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_extracted_data'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_extracted_data')
    op.drop_table('resume_embeddings')
    op.drop_table('interview_questions')
    op.drop_table('candidate_similarity')
    op.drop_table('candidate_rankings')
    op.drop_table('candidate_ai_analysis')
    op.drop_table('resume_documents')
    op.drop_table('job_embeddings')
    op.drop_table('ai_logs')
    # ### end Alembic commands ###
