"""add_company_id_to_audit_logs

Revision ID: c5e3e22ccb2f
Revises: 1dc109f7a733
Create Date: 2026-07-20 15:57:31.053201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e3e22ccb2f'
down_revision: Union[str, None] = '1dc109f7a733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_audit_logs_company_id_companies'), 'audit_logs', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_audit_logs_company_id_companies'), 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'company_id')
    # ### end Alembic commands ###
