"""add_budget_to_departments

Revision ID: c70e966a30a7
Revises: 8b7c6d5e4f3a
Create Date: 2026-07-18 11:12:05.008738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70e966a30a7'
down_revision: Union[str, None] = '8b7c6d5e4f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('budget', sa.Numeric(precision=14, scale=2), server_default=sa.text('0.0'), nullable=True))
    op.drop_index(op.f('ix_employees_verification_status'), table_name='employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employees_verification_status'), 'employees', ['verification_status'], unique=False)
    op.drop_column('departments', 'budget')
    # ### end Alembic commands ###
