"""Enums and constant values for Employee schemas."""

GENDER_VALUES = {"MALE", "FEMALE", "OTHER"}
BLOOD_GROUP_VALUES = {"A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"}
MARITAL_STATUS_VALUES = {"SINGLE", "MARRIED", "DIVORCED", "WIDOWED"}
EMPLOYMENT_TYPE_VALUES = {"FULL_TIME", "PART_TIME", "CONTRACT", "INTERN"}
EMPLOYMENT_STATUS_VALUES = {"PROBATION", "CONFIRMED", "NOTICE_PERIOD", "ACTIVE", "INACTIVE", "SUSPENDED", "TERMINATED", "RESIGNED", "ONBOARDING", "ON_LEAVE"}
DOCUMENT_TYPE_VALUES = {"AADHAAR", "PAN", "PASSPORT", "DRIVING_LICENSE", "VOTER_ID", "OTHER"}
ADDRESS_TYPE_VALUES = {"CURRENT", "PERMANENT"}
PROFICIENCY_VALUES = {"BEGINNER", "INTERMEDIATE", "ADVANCED", "EXPERT"}
ACCOUNT_TYPE_VALUES = {"SAVINGS", "CURRENT"}
EMPLOYEE_STATUS_VALUES = {
    "DRAFT", "CREATED", "INVITATION_SENT", "EMAIL_VERIFIED",
    "PASSWORD_CREATED", "ONBOARDING_PENDING", "DOCUMENT_PENDING",
    "UNDER_VERIFICATION", "ACTIVE", "INACTIVE", "TERMINATED",
    "PROBATION", "NOTICE_PERIOD", "SUSPENDED", "RESIGNED", "RETIRED",
    "LEAVE_OF_ABSENCE", "ON_LEAVE", "ONBOARDING", "PENDING", "CONFIRMED",
}
ONBOARDING_STEP_STATUS_VALUES = {"PENDING", "SUBMITTED", "VERIFIED", "REJECTED"}
ROLE_VALUES = {"super_admin", "hr_admin", "manager", "employee", "executive", "it_admin"}

VERIFICATION_STATUS_VALUES = {
    "PENDING_ADMIN_CREATED", "PENDING_SELF_ONBOARDING", "VERIFIED", "CERTIFIED",
}

# Allowed metadata keys per role (used for validation in schema)
ROLE_METADATA_KEYS: dict[str, set[str]] = {
    "super_admin": set(),
    "hr_admin": set(),
    "manager": {
        "budget_authority_limit", "approval_levels",
    },
    "employee": set(),
    "executive": set(),
    "it_admin": set(),
}

