"""Generate the complete, production-ready README.md for OFC360 Backend."""

import json
import os
import re

def build_readme():
    endpoints_data = json.load(open("categorized_endpoints_clean.json", encoding="utf-8"))

    doc = []

    # Title
    doc.append("# OFC360 Backend")
    doc.append("")
    doc.append("> **Enterprise Human Resources Management & Organizational Intelligence Platform**")
    doc.append("> High-performance, multi-tenant backend built with FastAPI, SQLAlchemy 2.0 (AsyncPG), PostgreSQL 16, Redis 7, Celery 5, and local AI runtime integration.")
    doc.append("")

    # Section 1
    doc.append("## 1. Project Overview")
    doc.append("")
    doc.append("OFC360 Backend is the central application server and data layer for the OFC360 enterprise platform. It delivers complete automation and intelligence for core human resource operations, workforce lifecycle, payroll accounting, statutory compliance, talent acquisition, performance reviews, document verification, real-time collaboration, and localized enterprise AI capabilities.")
    doc.append("")
    doc.append("### Key Backend Responsibilities")
    doc.append("- **Core HR Lifecycle & Multi-Tenancy**: Complete management of organizations, departments, designations, employees, managers, assets, and hierarchy with automatic tenant data isolation via SQLAlchemy ORM event interceptors.")
    doc.append("- **Authentication & Security**: Multi-tenant authentication, RS256 asymmetric JWT signing, refresh token rotation with grace period, Redis-backed stateless token blacklisting, and role-based access control (RBAC) across six canonical roles.")
    doc.append("- **Payroll Processing & Statutory Compliance**: End-to-end salary calculations, pay cycles, earnings/deductions, overtime, bonuses, advance loans, Indian statutory compliance (PF ECR, ESI, Professional Tax, TDS Section 192), bank advice files (HDFC, ICICI, SBI, Generic NEFT), and batch payslip generation.")
    doc.append("- **Recruitment & Applicant Tracking (ATS)**: Job requisitions, public career portal, application pipelines, candidate sourcing, interview scheduling with scorecards, offer letter management, and automated resume screening.")
    doc.append("- **Time & Attendance Tracking**: Shift management, timesheets, check-in/out logging, attendance regularization requests, break tracking, and biometric face recognition verification using OpenCV, dlib, and deep face embeddings.")
    doc.append("- **Document Management & Automated OCR**: Multi-version document store, template generation, PDF manipulation, digital signatures, expiry alerts, and OCR document extraction.")
    doc.append("- **Enterprise Collaboration & Helpdesk**: Real-time communication channels, 1-on-1 direct messaging, team channels, WebRTC call signaling, announcements, company news, polls, and an internal ticketing helpdesk.")
    doc.append("- **Local AI & Intelligent Automation**: Powered strictly by an on-premise Ollama runtime (Qwen 3 / Llama 3.1 / Nomic Embed) to guarantee strict zero-data-leakage compliance. Cloud LLM providers are explicitly disabled.")
    doc.append("")
    doc.append("### API Architecture & Communication")
    doc.append("- **API Versioning**: Standardized RESTful APIs organized under `/api/v1` (Core HR, Auth, Management, AI Hub) and `/api/v2` (Advanced Intelligence, Document Intelligence, Copilots, Analytics).")
    doc.append("- **Response Envelope**: Universal `APIResponse[T]` schema (`success`, `message`, `data`, `errors`) with dual-key casing support (`snake_case` and `camelCase`) for seamless frontend interoperability.")
    doc.append("- **Background Processing**: Asynchronous distributed task execution via Celery with Redis broker and Redis result backend, featuring graceful synchronous fallbacks when Celery is not enabled.")
    doc.append("")

    # Section 2
    doc.append("## 2. Tech Stack")
    doc.append("")
    doc.append("The technology stack is verified directly from `requirements.txt`, `Dockerfile`, and application configuration:")
    doc.append("")
    doc.append("| Layer | Technology | Version | Purpose |")
    doc.append("| --- | --- | --- | --- |")
    doc.append("| **Runtime** | Python | `3.11-slim-bookworm` | Base application runtime environment |")
    doc.append("| **Web Framework** | FastAPI | `>=0.115.0` | Asynchronous high-performance REST API framework |")
    doc.append("| **ASGI Server** | Uvicorn (standard) | `>=0.30.0` | ASGI HTTP server with uvloop and httptools |")
    doc.append("| **ORM & DB Layer** | SQLAlchemy (asyncio) | `>=2.0.30` | Modern 2.0 async ORM with mapper relationships |")
    doc.append("| **Database Driver** | asyncpg | `>=0.29.0` | High-speed asynchronous PostgreSQL binary driver |")
    doc.append("| **Database** | PostgreSQL | `16-alpine` | Primary ACID relational database |")
    doc.append("| **Migrations** | Alembic | `>=1.13.2` | Database schema migrations with single-head lock |")
    doc.append("| **Data Validation** | Pydantic & Pydantic Settings | `>=2.8.0`, `>=2.3.0` | Strict schema validation and typed settings loading |")
    doc.append("| **Authentication** | python-jose & passlib[bcrypt] | `>=3.3.0`, `>=1.7.4` (bcrypt 4.0.1) | RS256/HS256 JWT tokens & Bcrypt (12 rounds) hashing |")
    doc.append("| **In-Memory Store** | Redis | `7-alpine` (redis-py `>=5.0.0`) | Token blacklist, rate limiting, and session caching |")
    doc.append("| **Task Queue** | Celery | `>=5.4.0` | Distributed asynchronous background worker queue |")
    doc.append("| **Biometrics & CV** | dlib, face_recognition, OpenCV | `20.0.1`, `1.3.0`, `>=4.10.0.84` | Facial recognition, attendance biometrics, QR codes |")
    doc.append("| **Document Processing** | ReportLab, openpyxl, pypdf, python-docx | `>=4.2.0`, `>=3.1.5`, `>=1.16.2`, `>=1.1.2` | PDF payslip generation, Excel export, docx extraction |")
    doc.append("| **Data Science** | pandas, numpy | `>=2.2.0`, `>=1.26.0,<2.0.0` | Payroll calculations, analytics, and metrics aggregation |")
    doc.append("| **Local AI Runtime** | Ollama | Host daemon (`qwen3:30b`) | Exclusively supported local LLM provider for zero data leak |")
    doc.append("| **Cloud Storage** | Cloudinary | `>=1.45.0` | Document, logo, and avatar asset cloud hosting |")
    doc.append("| **Payment Gateway** | Razorpay SDK | `>=1.4.1` | Order creation, verification, and webhooks |")
    doc.append("| **Testing** | pytest & pytest-asyncio | `>=8.0.0`, `>=0.23.0` | 72 automated test suites with async event loop |")
    doc.append("")
    doc.append("> [!NOTE]")
    doc.append("> **AI Provider Status**: External cloud LLM providers (OpenAI, Anthropic Claude, Google Gemini, OpenRouter) are **intentionally disabled** in the codebase. All AI capabilities are powered strictly by the local Ollama runtime to protect sensitive employee records and payroll data.")
    doc.append("")

    # Section 3
    doc.append("## 3. Architecture")
    doc.append("")
    doc.append("The OFC360 backend is designed using a clean, layered architecture with strict separation of concerns, request-scoped async database sessions, repository abstraction, business logic encapsulation in services, and automated middleware.")
    doc.append("")
    doc.append("```mermaid")
    doc.append("flowchart TD")
    doc.append("    Client[\"Frontend Client (Browser / Mobile / Public Portal)\"]")
    doc.append("    ")
    doc.append("    subgraph NetworkEdge [\"Edge & Middleware Layer\"]")
    doc.append("        CORS[\"CORS Middleware (Outermost ASGI Layer)\"]")
    doc.append("        SecurityHeaders[\"Security Headers Middleware\"]")
    doc.append("        RateLimit[\"Redis Sliding Window Rate Limiter\"]")
    doc.append("        AuthMiddleware[\"JWT Bearer & Cookie Authentication\"]")
    doc.append("        TenantCtx[\"Tenant Context Provider (tenant_id_ctx)\"]")
    doc.append("    end")
    doc.append("    ")
    doc.append("    subgraph APILayer [\"FastAPI Application Routers\"]")
    doc.append("        V1Routers[\"API v1 Routers (/api/v1/*)\"]")
    doc.append("        V2Routers[\"API v2 Routers (/api/v2/*)\"]")
    doc.append("        CoreRouters[\"Core HRMS & Public Routers (/api/*)\"]")
    doc.append("    end")
    doc.append("    ")
    doc.append("    subgraph LogicLayer [\"Service & Repository Layer\"]")
    doc.append("        Services[\"Business Logic Services\"]")
    doc.append("        Repos[\"Domain Repositories\"]")
    doc.append("    end")
    doc.append("    ")
    doc.append("    subgraph DataIsolation [\"SQLAlchemy 2.0 Multi-Tenancy Layer\"]")
    doc.append("        ORMInterceptor[\"SQLAlchemy do_orm_execute Event (with_loader_criteria)\"]")
    doc.append("        FlushInterceptor[\"SQLAlchemy before_flush Event (assign company_id)\"]")
    doc.append("    end")
    doc.append("    ")
    doc.append("    subgraph Persistence [\"Data Stores & Caching\"]")
    doc.append("        PostgreSQL[(\"PostgreSQL 16 Database\")]")
    doc.append("        Redis[(\"Redis 7 (Tokens, Cache, Rate Limits)\")]")
    doc.append("    end")
    doc.append("    ")
    doc.append("    subgraph AsyncWorkers [\"Background Tasks & External Services\"]")
    doc.append("        Celery[\"Celery Background Workers\"]")
    doc.append("        Ollama[\"Local Ollama LLM Service\"]")
    doc.append("        SMTP[\"SMTP Mail Server\"]")
    doc.append("        Cloudinary[\"Cloudinary Media Store\"]")
    doc.append("    end")
    doc.append("    ")
    doc.append("    Client --> CORS")
    doc.append("    CORS --> SecurityHeaders")
    doc.append("    SecurityHeaders --> RateLimit")
    doc.append("    RateLimit --> AuthMiddleware")
    doc.append("    AuthMiddleware --> TenantCtx")
    doc.append("    TenantCtx --> V1Routers & V2Routers & CoreRouters")
    doc.append("    V1Routers & V2Routers & CoreRouters --> Services")
    doc.append("    Services --> Repos")
    doc.append("    Repos --> ORMInterceptor")
    doc.append("    ORMInterceptor --> PostgreSQL")
    doc.append("    FlushInterceptor --> PostgreSQL")
    doc.append("    AuthMiddleware -. Token Revocation & Blocklist .-> Redis")
    doc.append("    Services -. Enqueue Jobs .-> Celery")
    doc.append("    Celery -. Broker & Backend .-> Redis")
    doc.append("    Services -. AI Queries .-> Ollama")
    doc.append("    Services -. Transactional Emails .-> SMTP")
    doc.append("    Services -. Static Media .-> Cloudinary")
    doc.append("```")
    doc.append("")
    doc.append("### Architectural Workflow")
    doc.append("1. **Request Ingestion**: Incoming HTTP requests hit FastAPI through the outermost `CORSMiddleware`, which handles OPTIONS preflight immediately with 200/204 responses.")
    doc.append("2. **Security & Rate Limiting**: Request passes through `SecurityHeadersMiddleware` (X-Frame-Options, CSP, HSTS) and `RateLimitMiddleware` (backed by Redis with an in-memory fallback).")
    doc.append("3. **Authentication & Tenant Binding**: `get_current_user_claims` resolves the RS256 Bearer JWT, validates token expiration, checks the Redis blacklist for revocations, extracts `company_id`, and sets the context variable `tenant_id_ctx`.")
    doc.append("4. **Service Execution**: Routers delegate directly to business services (`AuthService`, `PayrollRunService`, `RecruitmentService`, `EmployeeService`, etc.).")
    doc.append("5. **Multi-Tenant Data Isolation**: When database queries execute, SQLAlchemy's `do_orm_execute` event automatically injects a `with_loader_criteria` filter (`company_id == tenant_id_ctx.get()`) into all queries unless explicit administrative bypass (`bypass_tenant=True`) is specified. During insert/update, `before_flush` automatically attaches the tenant ID.")
    doc.append("6. **Background Offloading**: Heavy compute operations (payroll batch calculation, PDF generation, bulk email dispatch, resume parsing) are pushed to Celery queues over Redis or executed asynchronously via Python event loops.")
    doc.append("")

    # Section 4
    doc.append("## 4. Project Structure")
    doc.append("")
    doc.append("```text")
    doc.append("apiofc360/")
    doc.append("├── app/                                  # Core application source code")
    doc.append("│   ├── agents/                           # Autonomous AI agent implementations")
    doc.append("│   ├── analytics/                        # Aggregation logic and analytical query builders")
    doc.append("│   ├── api/                              # REST API endpoint routers")
    doc.append("│   │   ├── cto/                          # CTO and engineering executive dashboard routes")
    doc.append("│   │   ├── payroll/                      # Comprehensive payroll API submodules")
    doc.append("│   │   ├── v1/                           # API Version 1 routers and AI Hub submodules")
    doc.append("│   │   │   ├── ai_hub/                   # AI Gateway endpoints (15 specialized sub-routers)")
    doc.append("│   │   │   └── payroll/                  # Legacy v1 payroll calculation and run routes")
    doc.append("│   │   ├── v2/                           # API Version 2 routers (Copilots, Intelligence, Analytics)")
    doc.append("│   │   ├── auth.py                       # Authentication, registration, OTP, tokens, password reset")
    doc.append("│   │   ├── employees.py                  # Employee directory, personal profiles, documents, skills")
    doc.append("│   │   ├── hr_admin.py                   # HR Admin administrative operations & employee provisioning")
    doc.append("│   │   ├── managers.py                   # Manager team dashboard, approvals, direct reports")
    doc.append("│   │   ├── departments.py                # Department CRUD, headcount breakdown, assignments")
    doc.append("│   │   ├── jobs.py & recruitment.py      # ATS, job postings, requisitions, candidate sourcing")
    doc.append("│   │   ├── applications.py               # Candidate job applications and resume attachments")
    doc.append("│   │   ├── interviews.py                 # Interview rounds, scheduling, scorecards")
    doc.append("│   │   ├── onboarding.py                 # Employee onboarding steps, checklist, document upload")
    doc.append("│   │   ├── timesheets.py & attendance.py # Attendance logs, shifts, breaks, regularization")
    doc.append("│   │   ├── leaves.py                     # Leave types, balances, applications, approvals")
    doc.append("│   │   ├── assets.py                     # Asset inventory, assignment history, maintenance")
    doc.append("│   │   ├── exits.py                      # Resignation, clearance, exit interview, FnF settlements")
    doc.append("│   │   ├── documents.py                  # Document categories, templates, e-signatures, audit logs")
    doc.append("│   │   ├── connect.py                    # Real-time chat, channels, calls, meetings, file sharing")
    doc.append("│   │   ├── helpdesk.py                   # Internal employee support tickets, comments, FAQs")
    doc.append("│   │   ├── super_admin.py                # Platform Super Admin endpoints & tenant company management")
    doc.append("│   │   ├── billing.py & payments.py      # Razorpay payment orders, subscription tiers, invoices")
    doc.append("│   │   └── settings.py                   # Company settings, security policies, IP whitelist, MFA")
    doc.append("│   ├── attendance/                       # Attendance sub-package (models, schemas, routers)")
    doc.append("│   ├── core/                             # Core configuration, security, and exception handling")
    doc.append("│   │   ├── config.py                     # Pydantic BaseSettings loading from environment")
    doc.append("│   │   ├── exceptions.py                 # AppException hierarchy and global exception handlers")
    doc.append("│   │   ├── permissions.py                # Catalog of roles and permissions")
    doc.append("│   │   ├── rate_limiter.py               # Redis sliding window rate limiter and middleware")
    doc.append("│   │   ├── rbac.py                       # FastAPI role verification dependencies (require_*)")
    doc.append("│   │   ├── redis_client.py               # Async Redis connection pool and token blacklist helper")
    doc.append("│   │   └── security.py                   # Passlib bcrypt password hashing and cryptographic utils")
    doc.append("│   ├── db/                               # Database setup, sessions, base classes, and events")
    doc.append("│   │   ├── base.py                       # Declarative Base, TimestampMixin, UUID generator, tenant_id_ctx")
    doc.append("│   │   └── database.py                   # create_async_engine, async_sessionmaker, ORM event hooks")
    doc.append("│   ├── llm/                              # Local LLM client, router, prompts, and Ollama registry")
    doc.append("│   ├── middleware/                       # ASGI Middlewares (Auth, Timing, Security Headers)")
    doc.append("│   ├── models/                           # 244 SQLAlchemy database model definitions")
    doc.append("│   │   ├── user/                         # User model package, mixins, and canonical UserRole enum")
    doc.append("│   │   ├── payroll.py & payroll_models.py# Enterprise payroll, payslips, bank batches, tax settings")
    doc.append("│   │   ├── recruitment.py                # Jobs, candidates, applications, interviews, scorecards")
    doc.append("│   │   ├── employee.py                   # Employee profile, addresses, bank accounts, documents")
    doc.append("│   │   ├── connect.py                    # Channels, direct messages, calls, meetings, attachments")
    doc.append("│   │   └── ...                           # Other domain models")
    doc.append("│   ├── ocr/                              # OCR engine drivers (PaddleOCR, EasyOCR, Tesseract, Document AI)")
    doc.append("│   ├── rag/                              # Vector embedding store and document retrieval")
    doc.append("│   ├── repositories/                     # Data access layer abstracting direct SQLAlchemy queries")
    doc.append("│   ├── routers/                          # Core HRMS module routers")
    doc.append("│   ├── schemas/                          # Pydantic request and response validation models")
    doc.append("│   ├── services/                         # Business logic services (EmailService, PayrollService, etc.)")
    doc.append("│   ├── templates/                        # HTML email templates (activation, OTP, welcome, onboarding)")
    doc.append("│   ├── utils/                            # Helper utilities (JWT encoder/decoder, formatters, dates)")
    doc.append("│   ├── validators/                       # Input validation rules (phone numbers, passwords, emails)")
    doc.append("│   ├── workers/                          # Celery background tasks (payroll, resume, notification)")
    doc.append("│   └── main.py                           # FastAPI application factory, lifespan handler, route mounting")
    doc.append("├── alembic/                              # Alembic database migrations")
    doc.append("│   ├── versions/                         # 90 version migration scripts")
    doc.append("│   └── env.py                            # Migration environment with asyncpg NullPool runner")
    doc.append("├── scripts/                              # Operational, diagnostic, and deployment automation scripts")
    doc.append("│   ├── check_migrations.py               # Validates single Alembic head and zero divergence")
    doc.append("│   ├── run_migrations.py                 # Runs migrations under PostgreSQL advisory lock")
    doc.append("│   ├── predeploy.sh                      # Zero-downtime deployment script with sanity checks")
    doc.append("│   └── install_dlib.py                   # Pre-compiled / parallel dlib provisioning helper")
    doc.append("├── tests/                                # 72 comprehensive automated test suites")
    doc.append("├── uploads/                              # Mounted local storage for avatars, documents, attachments")
    doc.append("├── Dockerfile                            # Multi-stage production container build")
    doc.append("├── docker-compose.yml                    # Multi-container orchestration (api, db, redis, celery_worker)")
    doc.append("├── docker-entrypoint.sh                  # Container startup entrypoint with automated migration runner")
    doc.append("├── Makefile                              # Make tasks (db-check)")
    doc.append("├── pytest.ini                            # Pytest configuration with async loop scoping")
    doc.append("├── requirements.txt                      # Production Python dependencies")
    doc.append("└── requirements-dev.txt                  # Development and test dependencies")
    doc.append("```")
    doc.append("")

    # Section 5
    doc.append("## 5. API Architecture")
    doc.append("")
    doc.append("### API Versioning & Routing")
    doc.append("- **Prefix `/api/v1`**: Core enterprise HRMS modules, authentication, onboarding, recruitment, timesheets, payroll runs, settings, and the unified AI Hub Gateway.")
    doc.append("- **Prefix `/api/v2`**: Advanced organizational intelligence, executive copilots, behavioral interview bot, mood detection, employee digital twins, and specialized intelligence engines.")
    doc.append("- **Direct `/api/*` & Unprefixed Endpoints**: Public career portal (`/api/careers`), public payment webhooks (`/payments/webhook`), system health checks (`/health`, `/health/ready`), and diagnostic tools.")
    doc.append("")
    doc.append("### Request Validation & Response Schema")
    doc.append("All endpoints validate incoming JSON payloads through Pydantic v2 models. Responses are serialized into the standard envelope `APIResponse[T]`:")
    doc.append("```json")
    doc.append("{")
    doc.append('  "success": true,')
    doc.append('  "message": "Operation completed successfully.",')
    doc.append('  "data": { ... },')
    doc.append('  "errors": null')
    doc.append("}")
    doc.append("```")
    doc.append("")
    doc.append("### Error Envelope")
    doc.append("When business exceptions or validation errors occur, responses adhere to the unified error contract with appropriate HTTP status codes:")
    doc.append("```json")
    doc.append("{")
    doc.append('  "success": false,')
    doc.append('  "message": "Validation failed.",')
    doc.append('  "data": null,')
    doc.append('  "errors": [')
    doc.append('    {"field": "email", "message": "Invalid email address format."}')
    doc.append("  ],")
    doc.append('  "code": "VALIDATION_FAILED"')
    doc.append("}")
    doc.append("```")
    doc.append("")
    doc.append("### Pagination, Filtering & Sorting")
    doc.append("- **Pagination**: Supported across listing endpoints using `limit` (default: 20, max: 100) and `offset` (default: 0) or `page` and `page_size` query parameters. Response payloads include total counts, total pages, and current page metadata.")
    doc.append("- **Filtering**: Query parameters support filtering by `department_id`, `status`, `role`, `employment_type`, `date_from`, `date_to`, and text `search`.")
    doc.append("- **Sorting**: Handled through `sort_by` (field name) and `sort_order` (`asc` or `desc`).")
    doc.append("")
    doc.append("### Rate Limiting")
    doc.append("- **Global Middleware**: `RateLimitMiddleware` enforces sliding window quotas via Redis: 100 requests/minute and 2,000 requests/hour per client IP or authenticated user ID.")
    doc.append("- **Sensitive Auth Limits**: Login is limited to 5 attempts per 60 seconds (`LOGIN_RATE_LIMIT_LIMIT=5`, `LOGIN_RATE_LIMIT_WINDOW=60`); registration is limited to 5 per minute (`REGISTER_RATE_LIMIT=\"5/minute\"`); OTP resend has a 30-second cooldown (`OTP_RESEND_COOLDOWN_SECONDS=30`) with a maximum of 5 verification attempts (`OTP_MAX_ATTEMPTS=5`).")
    doc.append("- **AI Endpoints**: Rate limited to 30 requests/minute and 500 requests/hour per user (`AI_RATE_LIMIT_PER_MINUTE=30`).")
    doc.append("")

    # Section 6
    doc.append("## 6. API Endpoints")
    doc.append("")
    doc.append("The backend exposes 1,843 live registered routes across 115 unique tags. Below is the complete endpoint directory grouped by business domain. Every endpoint has been verified against the active source code.")
    doc.append("")

    # Map modules to section headings
    module_headings = [
        ("Authentication", "### Authentication", endpoints_data["Authentication"]),
        ("Users", "### Users", endpoints_data["Users"]),
        ("Workforce", "### Workforce", endpoints_data["Workforce"]),
        ("Recruitment", "### Recruitment", endpoints_data["Recruitment"]),
        ("Onboarding", "### Onboarding", endpoints_data["Onboarding"]),
        ("Attendance", "### Attendance", endpoints_data["Attendance"]),
        ("Leave", "### Leave", endpoints_data["Leave"]),
        ("Payroll", "### Payroll", endpoints_data["Payroll"]),
        ("Performance", "### Performance", endpoints_data["Performance"]),
        ("Documents", "### Documents", endpoints_data["Documents"]),
        ("Compliance", "### Compliance", endpoints_data["Compliance"]),
        ("Reports", "### Reports", endpoints_data["Reports"]),
        ("AI/Intelligence", "### AI/Intelligence", endpoints_data["AI/Intelligence"]),
        ("Integrations", "### Integrations", endpoints_data["Integrations"]),
        ("Admin", "### Admin", endpoints_data["Admin"]),
        ("Collaboration & Helpdesk", "### Collaboration & Helpdesk", endpoints_data["Collaboration & Helpdesk"]),
    ]

    for mod_name, heading, ep_list in module_headings:
        doc.append(f"{heading} ({len(ep_list)} endpoints)")
        doc.append("")
        doc.append("| Method | Endpoint | Authentication | Purpose |")
        doc.append("| --- | --- | --- | --- |")
        for ep in ep_list:
            m = ep["method"]
            p = ep["endpoint"]
            a = ep["auth"]
            pur = ep["purpose"].replace("|", "\\|").replace("\n", " ").strip()
            doc.append(f"| `{m}` | `{p}` | {a} | {pur} |")
        doc.append("")

    # Section 7
    doc.append("## 7. Authentication & Authorization")
    doc.append("")
    doc.append("### Authentication Flows")
    doc.append("1. **Registration (`POST /api/v1/auth/register`)**: Creates an inactive user account, generates a 6-digit cryptographically secure OTP, hashes the OTP, and sends a verification email via SMTP.")
    doc.append("2. **Email Verification (`POST /api/v1/auth/verify-email`)**: Verifies the OTP within the 10-minute expiry window. Upon success, marks the account verified and active.")
    doc.append("3. **Login (`POST /api/v1/auth/login`)**: Validates email/password against bcrypt hash (12 rounds). Verifies account is active, verified, not suspended/terminated, and associated employee/manager profile is active. Returns an RS256 Bearer access token and sets an HttpOnly refresh cookie.")
    doc.append("4. **Session Refresh (`POST /api/v1/auth/refresh-token`)**: Supports refresh via request body or HttpOnly cookie (`ofc360_refresh_token`). Issues a fresh access token and rotates the refresh token with a 15-second grace window to prevent race conditions during rapid concurrent client refreshes.")
    doc.append("5. **Password Management (`/forgot-password`, `/reset-password`, `/change-password`)**: Rate-limited password reset flow with secure single-use reset tokens.")
    doc.append("6. **Logout (`POST /api/v1/auth/logout`)**: Adds the access token to the Redis blacklist with a TTL matching token expiry, revokes the refresh token in PostgreSQL, and clears all session cookies.")
    doc.append("7. **Social OAuth (`/github`, `/google`)**: Secure OAuth callback exchange for single sign-on.")
    doc.append("")
    doc.append("### Canonical Role-Based Access Control (RBAC)")
    doc.append("OFC360 implements six canonical system roles defined in `RoleEnum` (`app/models/user/role.py`):")
    doc.append("")
    doc.append("| Role | Code | Scope & Privileges |")
    doc.append("| --- | --- | --- |")
    doc.append("| **Super Admin** | `super_admin` | Global platform administration. Immutable security lock: strictly restricted to `superadmin@ofc360.com`. Manages tenant companies, platform health, and global organizations. |")
    doc.append("| **HR Admin** | `hr_admin` | Organization-level HR administration. Full authority over company employees, payroll execution, recruitment pipelines, leave policies, and company documents. |")
    doc.append("| **Manager** | `manager` | Team management. Oversees direct reports, approves leave and regularization requests, conducts performance evaluations, and tracks team attendance. |")
    doc.append("| **Employee** | `employee` | Standard employee self-service. Access to personal attendance, timesheets, leave applications, payslip downloads, personal documents, and company connect. |")
    doc.append("| **Executive** | `executive` | C-Suite leadership (CEO, CTO, CFO, COO, CMO, etc.). Access to company-wide analytics, workforce forecasting, executive copilots, and strategic reporting. |")
    doc.append("| **IT Admin** | `it_admin` | Technical administration. Manages system settings, IP whitelists, security audit logs, MFA enforcement, and active user sessions. |")
    doc.append("")
    doc.append("> [!IMPORTANT]")
    doc.append("> **Single Super Admin Security Lock**: The platform enforces that only `superadmin@ofc360.com` can hold the `super_admin` role. Any attempt to elevate another account to `super_admin` or reassign the official email is blocked at both ORM validator and startup migration levels.")
    doc.append("")
    doc.append("### RBAC Dependency Checks")
    doc.append("Endpoints are guarded by specific FastAPI dependencies from `app/core/rbac.py`:")
    doc.append("- `require_super_admin`: Validates official Super Admin identity.")
    doc.append("- `require_hr_admin`: Allows `hr_admin` and `super_admin`.")
    doc.append("- `require_admin`: Allows `super_admin`, `hr_admin`, and `it_admin`.")
    doc.append("- `require_admin_or_manager`: Allows `super_admin`, `hr_admin`, `it_admin`, `manager`, and `executive`.")
    doc.append("- `require_executive`: Allows `executive`, `hr_admin`, and `super_admin`.")
    doc.append("- `require_it_admin`: Allows `it_admin` and `super_admin`.")
    doc.append("- `require_employee_or_above`: Allows any authenticated platform role.")
    doc.append("- `require_roles(*roles)`: Dynamic dependency factory for custom role sets.")
    doc.append("")

    # Section 8
    doc.append("## 8. Database")
    doc.append("")
    doc.append("### Database Architecture")
    doc.append("- **Engine**: PostgreSQL 16 managed through SQLAlchemy 2.0 with the asynchronous `asyncpg` driver.")
    doc.append("- **Connection Pooling**: `create_async_engine` configured with connection pool parameters:")
    doc.append("  - `pool_size = 5` (Default pool connections)")
    doc.append("  - `max_overflow = 5` (Burst connections under heavy concurrent loads)")
    doc.append("  - `pool_timeout = 30` (Seconds to wait for a connection before timing out)")
    doc.append("  - `pool_recycle = 300` (Recycles connections every 5 minutes to prevent stale sockets)")
    doc.append("  - `pool_pre_ping = True` (Tests connection liveness with `SELECT 1` before issuing to worker)")
    doc.append("- **Session Lifecycle**: Handled via `get_db_session` dependency. Every request gets an isolated `AsyncSession` (`expire_on_commit=False`, `autoflush=False`). Errors trigger automatic rollback.")
    doc.append("")
    doc.append("### Multi-Tenant Isolation Architecture")
    doc.append("OFC360 employs row-level multi-tenancy enforced at the SQLAlchemy ORM layer:")
    doc.append("1. **Context Variable (`tenant_id_ctx`)**: Set during request authentication to the authenticated user's `company_id`.")
    doc.append("2. **Global Query Interceptor (`do_orm_execute`)**: Automatically appends `with_loader_criteria` to every ORM query for entities containing a `company_id` column:")
    doc.append("   ```python")
    doc.append("   target_cls.company_id == tenant_id_ctx.get()")
    doc.append("   ```")
    doc.append("   This guarantees that no user can read another organization's records even if SQL queries omit the WHERE clause.")
    doc.append("3. **Automatic Assignment (`before_flush`)**: Automatically injects `obj.company_id = tenant_id_ctx.get()` on newly created records.")
    doc.append("4. **Administrative Bypass**: Platform Super Admin endpoints explicitly pass `execution_options(bypass_tenant=True)` to inspect global cross-company metrics.")
    doc.append("")

    # Section 9
    doc.append("## 9. Database Models")
    doc.append("")
    doc.append("The database schema comprises **244 tables** organized into 21 business domains:")
    doc.append("")
    doc.append("| Business Domain | Tables Count | Key Tables | Purpose & Core Entities |")
    doc.append("| --- | --- | --- | --- |")
    doc.append("| **Authentication & Security** | 20 | `users`, `user_sessions`, `refresh_tokens`, `otps`, `password_resets`, `user_mfa`, `security_roles`, `security_policies`, `ip_whitelist`, `security_audit_logs` | User identities, credential hashes, multi-factor auth, sessions, IP whitelists, and token lifecycle |")
    doc.append("| **Organization & Companies** | 10 | `companies`, `departments`, `company_settings`, `designations` | Multi-tenant organizations, organizational hierarchies, corporate configuration, and job designations |")
    doc.append("| **Employees & Core HR** | 15 | `employees`, `employee_addresses`, `employee_documents`, `employee_education`, `employee_experience`, `employee_skills`, `employee_emergency_contacts`, `employee_bank_accounts`, `employee_invitations` | Employee master profiles, statutory identifiers, qualifications, banking info, and invitations |")
    doc.append("| **Managers & Hierarchy** | 6 | `managers`, `manager_addresses`, `manager_documents`, `manager_education`, `manager_experience`, `manager_skills`, `hierarchy_audit_logs` | Management directory, departmental reporting relationships, and organizational hierarchy tracking |")
    doc.append("| **Recruitment & ATS** | 31 | `jobs`, `job_skills`, `job_requisitions`, `applications`, `application_documents`, `candidates`, `candidate_crm_notes`, `candidate_referrals`, `interviews`, `interview_rounds`, `offers`, `scorecard_templates`, `recruitment_vendors` | Complete hiring pipeline: job requisitions, candidate sourcing, interviews, evaluations, and offers |")
    doc.append("| **AI Recruitment & Screening** | 3 | `ai_resume_documents`, `candidate_match_scores`, `ai_screening_results`, `coding_assessment_records`, `hr_copilot_queries` | Automated resume parsing, candidate-job matching scores, AI screening summaries, and coding tests |")
    doc.append("| **Onboarding** | 2 | `onboarding_progress`, `employee_onboarding`, `employee_policy_acceptances` | New-hire onboarding workflows, task checklists, document submission verification, and policy sign-offs |")
    doc.append("| **Attendance & Time** | 8 | `attendances`, `attendance_breaks`, `attendance_regularization_requests`, `timesheets`, `timesheet_entries`, `shift_plans`, `shift_plan_entries`, `shifts` | Clock-in/out logging, geolocation/biometric data, break tracking, regularization, timesheets, and shift planning |")
    doc.append("| **Leave & Holidays** | 5 | `leave_requests`, `leave_policies`, `employee_leave_policies`, `holiday_calendar`, `holidays` | Leave balance tracking, annual accruals, leave requests, manager approval flows, and company holidays |")
    doc.append("| **Payroll & Compensation** | 26 | `payroll_runs`, `payroll_periods`, `payroll_run_employees`, `payslips`, `pay_components`, `compensations`, `compensation_revisions`, `variable_inputs`, `payment_batches`, `payment_batch_bank_files`, `full_and_final_settlements`, `salary_structures`, `statutory_compliance_configs`, `advance_loans`, `reimbursement_claims`, `bank_advice_files` | Comprehensive payroll processing engine: salary structures, earnings, deductions, PF/ESI/PT/TDS, bank disbursement advice, loans, and FnF |")
    doc.append("| **Performance & Goals** | 7 | `performance_review_cycles`, `employee_performance_goals`, `performance_reviews`, `performance_kpis`, `generated_goals`, `employee_productivity_logs`, `productivity_forecasting_runs` | Quarterly/annual review cycles, OKRs, KPI tracking, AI goal recommendations, and productivity metrics |")
    doc.append("| **Documents & Templates** | 16 | `document_categories`, `company_documents`, `document_templates`, `document_versions`, `document_signatures`, `document_verifications`, `document_expiry_tracking`, `document_audit_logs`, `document_ocr_records` | Document repository, version history, template merging, digital signatures, OCR records, and expiry alarms |")
    doc.append("| **Exit & Separation** | 4 | `employee_exits`, `knowledge_transfers`, `asset_returns`, `clearance_requests`, `exit_interviews`, `fnf_settlements`, `exit_documents` | Resignation lifecycle, multi-department clearance approvals, knowledge handover, and exit interviews |")
    doc.append("| **Calendar & Meetings** | 8 | `calendar_events`, `meetings`, `meeting_participants`, `calendar_notifications`, `event_reminders` | Corporate events, scheduling, calendar integrations, meeting participants, and automated notifications |")
    doc.append("| **Collaboration & Communication** | 18 | `connect_conversations`, `connect_conversation_participants`, `connect_channels`, `connect_channel_members`, `connect_messages`, `connect_message_reactions`, `connect_call_logs`, `connect_meetings`, `announcements`, `company_news`, `company_events`, `polls`, `notification_center` | Real-time chat, group channels, WebRTC call signaling, company announcements, news, and employee polls |")
    doc.append("| **Helpdesk & Support** | 7 | `helpdesk_tickets`, `helpdesk_comments`, `helpdesk_internal_notes`, `helpdesk_attachments`, `helpdesk_faqs` | Internal employee ticketing system, priority SLA tracking, attachments, private agent notes, and FAQs |")
    doc.append("| **AI Engines & Intelligence** | 25 | `ai_conversations`, `ai_messages`, `agent_runs`, `ai_compensation_recommendations`, `behavioural_interview_sessions`, `emotion_aware_chat_sessions`, `org_hierarchy_snapshots`, `skill_gap_analyses`, `employee_digital_twins`, `career_path_predictions`, `workforce_forecast_runs`, `hr_analytics_snapshots`, `hr_attrition_predictions` | Advanced intelligence modules: attrition risk forecasting, skill gap analysis, workforce planning, and copilot query history |")
    doc.append("| **Health & Wellness** | 3 | `employee_wellness_logs`, `wellness_escalation_rules`, `wellness_anonymous_chat_sessions`, `employee_health_records` | Confidential mental wellness logging, anonymous support chat, escalation triggers, and medical records |")
    doc.append("| **Compliance & Audit** | 26 | `compliance_records`, `compliance_audit_logs`, `compliance_obligations`, `compliance_documents`, `audit_logs`, `analysis_audit_logs` | Comprehensive enterprise audit trail capturing entity mutations, auth changes, and statutory compliance status |")
    doc.append("| **Billing & Subscriptions** | 1 | `subscriptions`, `payment_transactions` | Enterprise billing plans, seat allocation, subscription renewal status, and Razorpay transaction records |")
    doc.append("| **Assets Management** | 3 | `assets`, `asset_assignment_history`, `asset_maintenance_records` | IT and physical asset tracking, serial numbers, allocation history, return conditions, and maintenance |")
    doc.append("")

    # Section 10
    doc.append("## 10. Alembic Migrations")
    doc.append("")
    doc.append("Database migrations are managed via Alembic in `alembic/`. Schema modifications are strictly applied through migrations; direct database modifications or runtime schema creation (`Base.metadata.create_all`) are forbidden.")
    doc.append("")
    doc.append("### Key Migration Commands")
    doc.append("```bash")
    doc.append("# 1. Apply all pending migrations to the latest revision")
    doc.append("alembic upgrade head")
    doc.append("")
    doc.append("# 2. Generate a new revision after updating SQLAlchemy models")
    doc.append('alembic revision --autogenerate -m "describe_your_changes"')
    doc.append("")
    doc.append("# 3. Verify single head and check for schema drift (must report zero drift)")
    doc.append("alembic check")
    doc.append("")
    doc.append("# 4. Rollback one revision")
    doc.append("alembic downgrade -1")
    doc.append("")
    doc.append("# 5. Resolve multiple heads if branches diverge")
    doc.append('alembic merge heads -m "merge_divergent_heads"')
    doc.append("```")
    doc.append("")
    doc.append("### Production Migration Architecture")
    doc.append("In production and Docker environments, migrations run with **PostgreSQL Advisory Locking** to prevent race conditions during multi-instance rolling deployments:")
    doc.append("- `scripts/run_migrations.py`: Acquires lock `SELECT pg_advisory_lock(483921747)`, verifies that exactly one head exists (`alembic heads`), confirms database revision matches local scripts, executes `alembic upgrade head`, and releases the lock.")
    doc.append("- `docker-entrypoint.sh`: Automatically invokes `alembic upgrade head` before booting Uvicorn whenever `RUN_MIGRATIONS=true` is set.")
    doc.append("")

    # Section 11
    doc.append("## 11. Environment Variables")
    doc.append("")
    doc.append("All configuration parameters are defined in `app/core/config.py` and loaded from `.env`. Sensitive credentials must never be committed.")
    doc.append("")
    doc.append("| Variable | Required | Purpose | Example |")
    doc.append("| --- | --- | --- | --- |")
    doc.append("| `APP_NAME` | No | Display name of the application | `OFC HR – Office Function Consolidator` |")
    doc.append("| `APP_VERSION` | No | Application semantic version | `2.0.0` |")
    doc.append("| `ENVIRONMENT` | Yes | Runtime environment (`local`, `development`, `production`) | `production` |")
    doc.append("| `DEBUG` | No | Enable debug mode (disable in production) | `false` |")
    doc.append("| `ENABLE_DOCS` | No | Override for public docs (/docs, /redoc) | `false` |")
    doc.append("| `LOG_LEVEL` | No | Python logging verbosity (`DEBUG`, `INFO`, `WARNING`, `ERROR`) | `INFO` |")
    doc.append("| `DATABASE_URL` | **Yes** | Async PostgreSQL connection string | `postgresql+asyncpg://user:pass@host:5432/ofc360` |")
    doc.append("| `DB_POOL_SIZE` | No | SQLAlchemy connection pool size | `5` |")
    doc.append("| `DB_MAX_OVERFLOW` | No | SQLAlchemy maximum pool overflow | `5` |")
    doc.append("| `DB_POOL_TIMEOUT` | No | Connection acquisition timeout in seconds | `30` |")
    doc.append("| `DB_POOL_RECYCLE` | No | Connection recycling duration in seconds | `300` |")
    doc.append("| `FORCE_IPV4_DB` | No | Workaround for IPv6-only resolution issues | `false` |")
    doc.append("| `SECRET_KEY` | **Yes** | Symmetric secret key (32+ chars) for OTPs and sessions | `generate_via_openssl_rand_hex_32` |")
    doc.append("| `JWT_ALGORITHM` | No | Cryptographic algorithm for JWTs | `RS256` |")
    doc.append("| `JWT_PRIVATE_KEY` | **Yes (Prod)** | RSA Private Key (PEM format) for signing JWTs | `-----BEGIN RSA PRIVATE KEY-----...` |")
    doc.append("| `JWT_PUBLIC_KEY` | **Yes (Prod)** | RSA Public Key (PEM format) for verifying JWTs | `-----BEGIN PUBLIC KEY-----...` |")
    doc.append("| `ACCESS_TOKEN_EXPIRE_MINUTES` | No | Access token validity duration | `30` |")
    doc.append("| `REFRESH_TOKEN_EXPIRE_DAYS` | No | Refresh token validity duration | `30` |")
    doc.append("| `SUPER_ADMIN_PASSWORD` | **Yes (Prod)** | Initial password for `superadmin@ofc360.com` (12+ chars) | `strong_admin_password` |")
    doc.append("| `RESET_SUPER_ADMIN_PASSWORD` | No | Force-reset Super Admin password on next startup | `false` |")
    doc.append("| `REDIS_URL` | **Yes (Prod)** | Redis connection URL for token blacklist and caching | `redis://redis:6379/0` |")
    doc.append("| `CELERY_BROKER_URL` | No | Celery broker URL | `redis://redis:6379/1` |")
    doc.append("| `CELERY_RESULT_BACKEND` | No | Celery result backend URL | `redis://redis:6379/2` |")
    doc.append("| `USE_CELERY` | No | Toggle Celery async processing (falls back to sync if false) | `true` |")
    doc.append("| `BACKEND_CORS_ORIGINS` | No | JSON list or comma-separated list of allowed origins | `[\"https://app.ofc360.com\",\"http://localhost:8080\"]` |")
    doc.append("| `SMTP_HOST` | **Yes (Prod)** | SMTP relay server hostname | `smtp.sendgrid.net` |")
    doc.append("| `SMTP_PORT` | No | SMTP relay server port | `587` |")
    doc.append("| `SMTP_USERNAME` | **Yes (Prod)** | SMTP authentication username | `apikey` |")
    doc.append("| `SMTP_PASSWORD` | **Yes (Prod)** | SMTP authentication password or API key | `smtp_password` |")
    doc.append("| `SMTP_FROM_EMAIL` | No | Default outbound sender email address | `no-reply@ofc360.com` |")
    doc.append("| `SMTP_FROM_NAME` | No | Outbound sender display name | `OFC360 Portal` |")
    doc.append("| `SMTP_USE_TLS` | No | Enable STARTTLS (standard on port 587) | `true` |")
    doc.append("| `SMTP_USE_SSL` | No | Enable direct SSL (standard on port 465) | `false` |")
    doc.append("| `CLOUDINARY_CLOUD_NAME` | **Yes (Prod)** | Cloudinary cloud account name | `cloudinary_name` |")
    doc.append("| `CLOUDINARY_API_KEY` | **Yes (Prod)** | Cloudinary API key | `cloudinary_key` |")
    doc.append("| `CLOUDINARY_API_SECRET` | **Yes (Prod)** | Cloudinary API secret | `cloudinary_secret` |")
    doc.append("| `OLLAMA_ENABLED` | No | Enable local Ollama AI engine integration | `true` |")
    doc.append("| `OLLAMA_BASE_URL` | No | Ollama HTTP daemon endpoint | `http://host.docker.internal:11434` |")
    doc.append("| `OLLAMA_MODEL` | No | Primary LLM model name | `qwen3:30b` |")
    doc.append("| `OLLAMA_TIMEOUT` | No | Ollama inference timeout in seconds | `120` |")
    doc.append("| `RAZORPAY_KEY_ID` | No | Razorpay payment gateway Key ID | `rzp_live_key_id` |")
    doc.append("| `RAZORPAY_KEY_SECRET` | No | Razorpay payment gateway Key Secret | `rzp_live_secret` |")
    doc.append("| `RAZORPAY_WEBHOOK_SECRET` | No | Razorpay webhook signature validation secret | `rzp_webhook_secret` |")
    doc.append("| `GITHUB_CLIENT_ID` | No | GitHub OAuth application Client ID | `github_client_id` |")
    doc.append("| `GITHUB_CLIENT_SECRET` | No | GitHub OAuth application Client Secret | `github_client_secret` |")
    doc.append("| `GOOGLE_CLIENT_ID` | No | Google OAuth Client ID | `google_client_id` |")
    doc.append("| `GOOGLE_CLIENT_SECRET` | No | Google OAuth Client Secret | `google_client_secret` |")
    doc.append("")

    # Section 12
    doc.append("## 12. Local Development")
    doc.append("")
    doc.append("### Prerequisites")
    doc.append("- Python 3.11 (`python --version`)")
    doc.append("- PostgreSQL 16 (`psql --version`)")
    doc.append("- Redis 7 (`redis-server --version`)")
    doc.append("- C/C++ compiler and CMake (required to build `dlib` C-extensions for facial recognition)")
    doc.append("")
    doc.append("### Step-by-Step Setup")
    doc.append("```bash")
    doc.append("# 1. Navigate to the backend directory")
    doc.append("cd apiofc360")
    doc.append("")
    doc.append("# 2. Create and activate a Python 3.11 virtual environment")
    doc.append("python -m venv .venv")
    doc.append("# On Linux/macOS:")
    doc.append("source .venv/bin/activate")
    doc.append("# On Windows (PowerShell):")
    doc.append(".venv\\Scripts\\Activate.ps1")
    doc.append("")
    doc.append("# 3. Upgrade pip and build tools")
    doc.append('pip install --upgrade pip "setuptools<81" wheel')
    doc.append("")
    doc.append("# 4. Install dlib dependency")
    doc.append("python scripts/install_dlib.py")
    doc.append("")
    doc.append("# 5. Install Python dependencies")
    doc.append("pip install -r requirements.txt")
    doc.append("pip install -r requirements-dev.txt")
    doc.append("")
    doc.append("# 6. Configure environment variables")
    doc.append("cp .env.example .env")
    doc.append("# Edit .env with your local PostgreSQL and Redis credentials")
    doc.append("")
    doc.append("# 7. Apply database migrations")
    doc.append("alembic upgrade head")
    doc.append("")
    doc.append("# 8. Run database integrity and drift checks")
    doc.append("make db-check")
    doc.append("")
    doc.append("# 9. Start the local development server")
    doc.append("uvicorn app.main:app --reload --host 127.0.0.1 --port 8000")
    doc.append("```")
    doc.append("")

    # Section 13
    doc.append("## 13. Running the Backend")
    doc.append("")
    doc.append("### Development Server")
    doc.append("```bash")
    doc.append("uvicorn app.main:app --reload --host 0.0.0.0 --port 8000")
    doc.append("```")
    doc.append("")
    doc.append("### Production Server (Direct / VM)")
    doc.append("```bash")
    doc.append("uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4 --proxy-headers --forwarded-allow-ips='*'")
    doc.append("```")
    doc.append("")
    doc.append("### Celery Background Worker")
    doc.append("```bash")
    doc.append("celery -A app.workers.celery_app worker --loglevel=info --concurrency=4 -Q default,resume_parsing,notifications")
    doc.append("```")
    doc.append("")
    doc.append("### Docker Compose (Full Stack)")
    doc.append("```bash")
    doc.append("# Build and start PostgreSQL, Redis, FastAPI, and Celery Worker")
    doc.append("docker compose up -d --build")
    doc.append("")
    doc.append("# View live unified logs")
    doc.append("docker compose logs -f")
    doc.append("")
    doc.append("# Shut down services and preserve volumes")
    doc.append("docker compose down")
    doc.append("```")
    doc.append("")

    # Section 14
    doc.append("## 14. Background Jobs & Automation")
    doc.append("")
    doc.append("### Celery Architecture")
    doc.append("- **App Entry**: `app.workers.celery_app.celery_app`")
    doc.append("- **Broker**: Redis (`settings.CELERY_BROKER_URL`, default `redis://localhost:6379/1`)")
    doc.append("- **Result Backend**: Redis (`settings.CELERY_RESULT_BACKEND`, default `redis://localhost:6379/2`)")
    doc.append("- **Timeouts**: Soft time limit = 300s, hard time limit = 600s (`CELERY_TASK_TIME_LIMIT`).")
    doc.append("- **Task Routing**:")
    doc.append("  - `resume_parsing` queue: `app.workers.resume_tasks.parse_resume`, `generate_embedding`")
    doc.append("  - `notifications` queue: `app.workers.notification_tasks.send_email`")
    doc.append("  - `default` queue: `app.workers.payroll_tasks.*`")
    doc.append("")
    doc.append("### Payroll Batch Processing Engine")
    doc.append("> [!NOTE]")
    doc.append("> **Payroll Autopilot Status**: The codebase **does not** contain a headless auto-pilot cron daemon that executes payroll automatically without human initiation. Instead, the payroll automation engine is designed as an asynchronous, state-tracked batch processing pipeline:")
    doc.append("")
    doc.append("1. **Run Calculation (`process_payroll_run_task`)**: Triggered by HR Admin. Executes `PayrollRunService.execute_run_calculation`, consolidating attendance logs, overtime policies, bonus plans, deductions, and advance loan installments into gross/net salary calculations for all active employees.")
    doc.append("2. **Batch Payslip Generation (`generate_payslips_batch_task`)**: Asynchronously compiles ReportLab PDF payslips with company letterhead, storing paths and generating provision slips.")
    doc.append("3. **Bank Disbursement Advice (`generate_bank_file_task`)**: Generates structured bank advice files (HDFC, ICICI, SBI, and Generic NEFT format) for corporate net banking uploads.")
    doc.append("4. **Statutory Report Generation (`generate_statutory_report_task`)**: Generates ECR/ESI text files, PT challans, and Form 16 / TDS Section 192 quarterly reports.")
    doc.append("5. **State Tracking (`PayrollJobTracker`)**: Uses Redis keys `payroll:job:{job_id}` to store progress percentages (0-100%), error states, and processed record counts for UI polling.")
    doc.append("")
    doc.append("### In-Process Scheduled Background Loops")
    doc.append("Managed as background tasks on the FastAPI event loop during application startup (`app/main.py`):")
    doc.append("- `run_document_expiry_scheduler()`: Runs once every 24 hours (`await asyncio.sleep(86400)`). Scans active employee and company documents against `DOCUMENT_EXPIRY_WARNING_DAYS` (30 days), generates warning audit logs, and sends notification reminders.")
    doc.append("- `auto_screen_unscreened_leads()`: Executes 2 seconds after startup. Queries all candidate applications lacking match scores and initiates resume analysis and match evaluation.")
    doc.append("")

    # Section 15
    doc.append("## 15. Email System")
    doc.append("")
    doc.append("All outbound transactional emails are processed by `EmailService` (`app/services/email_service.py`):")
    doc.append("- **Transport**: Standard Python `smtplib` executed asynchronously in worker threads via `asyncio.to_thread(_send_via_smtp)` to ensure non-blocking HTTP request processing.")
    doc.append("- **Security Modes**: Supports STARTTLS (port 587, `SMTP_USE_TLS=true`) or direct SSL (port 465, `SMTP_USE_SSL=true`).")
    doc.append("- **Template Engine**: Custom regex-based rendering engine supporting variable replacement (`{{ key }}`), conditional blocks (`{% if key %}...{% else %}...{% endif %}`), and fallback plain-text conversion.")
    doc.append("- **Retry Policy**: Up to 3 attempts with exponential back-off (1s, 2s). Hard authentication errors or recipient rejections abort immediately without retrying.")
    doc.append("- **Local Dev Behavior**: When `ENVIRONMENT=local` or `DEBUG=true`, failed SMTP deliveries do not raise HTTP 500; instead, the email content is cleanly dumped to the terminal console (`[DEV EMAIL LOG]`) for rapid local testing.")
    doc.append("- **Transactional Templates**: Account verification OTP (`verify_email.html`), login OTP (`login_verify_otp.html`), welcome message (`welcome_email.html`), password reset token (`password_reset_email.html`), employee account activation (`employee_activation.html`), and onboarding invitation (`employee_onboarding_invite.html`).")
    doc.append("")

    # Section 16
    doc.append("## 16. CORS (Cross-Origin Resource Sharing)")
    doc.append("")
    doc.append("CORS is configured in `app/main.py` using Starlette's `CORSMiddleware`. It is registered as the **outermost ASGI layer** to guarantee that preflight `OPTIONS` requests receive immediate `200 OK` / `204 No Content` responses at the network edge before reaching authentication or rate limiters.")
    doc.append("")
    doc.append("### Supported Origins")
    doc.append("- **Production Origins**:")
    doc.append("  - `https://ofc360.com`")
    doc.append("  - `https://www.ofc360.com`")
    doc.append("  - `https://api.ofc360.com`")
    doc.append("  - `https://app.ofc360.com`")
    doc.append("  - `https://ofc360.vercel.app`")
    doc.append("- **Local Development Origins**:")
    doc.append("  - `http://localhost:8080`, `http://127.0.0.1:8080`")
    doc.append("  - `http://localhost:3000`, `http://127.0.0.1:3000`")
    doc.append("  - `http://localhost:5173`, `http://127.0.0.1:5173`")
    doc.append("  - `http://localhost:4173`, `http://127.0.0.1:4173`")
    doc.append("  - Subnet matching regex (`192.168.x.x`, `10.x.x.x`, `172.16-31.x.x`) for mobile and LAN testing.")
    doc.append("- **Behavior**:")
    doc.append("  - `allow_credentials = True`")
    doc.append("  - `allow_methods = [\"*\"]`")
    doc.append("  - `allow_headers = [\"*\"]`")
    doc.append("  - `expose_headers = [\"Authorization\", \"Content-Type\", \"Content-Disposition\", \"X-Process-Time\", \"X-RateLimit-Limit\", \"X-RateLimit-Remaining\"]`")
    doc.append("  - `max_age = 86400` (Preflight cache duration = 24 hours)")
    doc.append("")

    # Section 17
    doc.append("## 17. API Error Handling")
    doc.append("")
    doc.append("FastAPI application error handlers are centralized in `app/core/exceptions.py`:")
    doc.append("")
    doc.append("### Exception Hierarchy")
    doc.append("```text")
    doc.append("AppException (Base Exception)")
    doc.append("├── ValidationException (HTTP 400 - Business rule failure)")
    doc.append("├── BadRequestException (HTTP 400 - Malformed request)")
    doc.append("├── UnauthorizedException (HTTP 401 - Authentication missing or expired)")
    doc.append("├── ForbiddenException (HTTP 403 - Permission denied or inactive account)")
    doc.append("├── NotFoundException (HTTP 404 - Resource does not exist)")
    doc.append("├── ConflictException (HTTP 409 - Resource uniqueness conflict)")
    doc.append("└── DatabaseException (HTTP 500 - Internal database query failure)")
    doc.append("```")
    doc.append("")
    doc.append("### Handlers Installed")
    doc.append("- **`AppException` Handler**: Formats custom application exceptions into standard `APIResponse` envelopes.")
    doc.append("- **`RequestValidationError` Handler**: Catches Pydantic schema validation failures, extracts invalid field paths, and returns clean error lists under HTTP 422.")
    doc.append("- **`StarletteHTTPException` Handler**: Intercepts framework-level HTTP errors (404, 405, 500) and formats them into JSON envelopes.")
    doc.append("- **Global Unhandled Exception Handler**: Catches unexpected runtime crashes, masks sensitive internals in production (`Internal server error`), logs stack traces with request context, and ensures CORS headers are attached.")
    doc.append("")

    # Section 18
    doc.append("## 18. Security")
    doc.append("")
    doc.append("- **Password Hashing**: Implemented via Passlib with Bcrypt (`rounds=12`). Passwords are never logged or stored in plain text.")
    doc.append("- **Asymmetric JWT Signing (RS256)**: Tokens are signed with a 2048-bit RSA Private Key (`JWT_PRIVATE_KEY`) and verified using the corresponding Public Key (`JWT_PUBLIC_KEY`).")
    doc.append("- **Token Revocation & Blocklist**: Redis-backed stateless token blacklisting. When a user logs out or an administrator changes an account password, the token is added to `token:blacklist` and `user:{user_id}:revoked_before` is updated.")
    doc.append("- **Session Cookies**: In production, cookies enforce `__Host-` prefix, `Secure=True`, `HttpOnly=True`, and `SameSite=Strict`.")
    doc.append("- **SQL Injection Protections**: Powered strictly by SQLAlchemy 2.0 parameterized queries and ORM type binding. Zero raw string concatenation.")
    doc.append("- **Tenant Isolation Guardrails**: Automated query filtering prevents cross-tenant data leaks.")
    doc.append("- **File Upload Security**: Uploaded files are validated against allowed extensions (`.pdf`, `.doc`, `.docx`, `.png`, `.jpg`), file size limits (10MB-20MB), and sanitized filenames. Document upload directories (`/app/uploads/documents`) are **never mounted as public static directories**.")
    doc.append("- **Security Headers**: Injected on all HTTP responses: `X-Content-Type-Options: nosniff`, `X-Frame-Options: DENY`, `X-XSS-Protection: 1; mode=block`, and `Referrer-Policy: strict-origin-when-cross-origin`.")
    doc.append("")

    # Section 19
    doc.append("## 19. Docker")
    doc.append("")
    doc.append("### Multi-Stage Production Dockerfile")
    doc.append("The repository includes an optimized multi-stage `Dockerfile` based on `python:3.11-slim-bookworm`:")
    doc.append("1. **Stage 1 (Builder)**: Installs build essentials, cmake, pkg-config, OpenBLAS, LAPACK, and libpq. Compiles `dlib` with parallel C++ optimizations into a virtual environment `/opt/venv`.")
    doc.append("2. **Stage 2 (Runner)**: Minimal Debian runtime containing only shared libraries (`libpq5`, `libgl1`, `libopenblas0`, `curl`, `gosu`). Copies pre-compiled `/opt/venv`, creates non-root user `appuser` (UID 10001), and compiles Python bytecode with `compileall`.")
    doc.append("3. **Healthcheck Probe**: `curl -f http://localhost:8000/health || exit 1` every 15s.")
    doc.append("")
    doc.append("### Docker Compose Architecture (`docker-compose.yml`)")
    doc.append("")
    doc.append("| Service | Image / Build | Container Name | Ports | Healthcheck Probe |")
    doc.append("| --- | --- | --- | --- | --- |")
    doc.append("| `db` | `postgres:16-alpine` | `ofc360_db` | `127.0.0.1:5432:5432` | `pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}` |")
    doc.append("| `redis` | `redis:7-alpine` | `ofc360_redis` | `127.0.0.1:6379:6379` | `redis-cli ping` |")
    doc.append("| `api` | Built from `Dockerfile` | `ofc360_api` | `0.0.0.0:8000:8000` | `curl -f http://localhost:8000/health` |")
    doc.append("| `celery_worker` | Built from `Dockerfile` | `ofc360_celery_worker` | None (Internal) | `celery inspect ping` |")
    doc.append("")

    # Section 20
    doc.append("## 20. Testing")
    doc.append("")
    doc.append("Testing is orchestrated with `pytest` and `pytest-asyncio` (`pytest.ini`). The repository includes **72 comprehensive test suites** covering auth, RBAC, payroll, recruitment, attendance, documents, and migrations.")
    doc.append("")
    doc.append("### Test Execution Commands")
    doc.append("```bash")
    doc.append("# 1. Run all test suites")
    doc.append("pytest")
    doc.append("")
    doc.append("# 2. Run database migration and schema integrity tests (Makefile)")
    doc.append("make db-check")
    doc.append("")
    doc.append("# 3. Run specific test domains")
    doc.append("pytest tests/test_auth_endpoints_comprehensive.py -v")
    doc.append("pytest tests/test_payroll_full_suite.py -v")
    doc.append("pytest tests/test_super_admin_security_lock.py -v")
    doc.append("pytest tests/test_multi_tenant_data_isolation.py -v")
    doc.append("pytest tests/test_alembic_single_head.py -v")
    doc.append("")
    doc.append("# 4. Run tests with coverage report")
    doc.append("pytest --cov=app --cov-report=term-missing")
    doc.append("```")
    doc.append("")

    # Section 21
    doc.append("## 21. Deployment")
    doc.append("")
    doc.append("### Production Deployment Topology")
    doc.append("```text")
    doc.append("Vercel Frontend (app.ofc360.com)")
    doc.append("      │ HTTPS / WSS")
    doc.append("      ▼")
    doc.append("Reverse Proxy / Cloud Load Balancer (Nginx / Render Gateway)")
    doc.append("      │ Port 8000")
    doc.append("      ▼")
    doc.append("FastAPI Uvicorn Application (ofc360_api)")
    doc.append("      ├───────────────────────────────┐")
    doc.append("      ▼                               ▼")
    doc.append("PostgreSQL 16 Database        Redis 7 (Cache & Queues)")
    doc.append("                                      ▲")
    doc.append("                                      │ Tasks & Results")
    doc.append("                             Celery Background Worker")
    doc.append("                                      ▼")
    doc.append("                             Local Ollama Runtime (Host Port 11434)")
    doc.append("```")
    doc.append("")
    doc.append("### Automated Pre-Deployment Script (`scripts/predeploy.sh`)")
    doc.append("The repository includes a production deployment runner that guarantees zero downtime:")
    doc.append("1. Verifies/recreates virtual environment and upgrades pip.")
    doc.append("2. Installs requirements from `requirements.txt`.")
    doc.append("3. Pre-compiles all Python syntax via `python -m compileall -q app alembic`.")
    doc.append("4. Validates configuration settings without exposing secret values.")
    doc.append("5. Runs `python scripts/run_migrations.py` under an advisory lock.")
    doc.append("")

    # Section 22
    doc.append("## 22. Health Checks & Monitoring")
    doc.append("")
    doc.append("### Liveness Probe (`GET /health`)")
    doc.append("- **Path**: `GET /health` or `HEAD /health`")
    doc.append("- **Authentication**: Public (None)")
    doc.append("- **Behavior**: Executes `SELECT 1` against PostgreSQL.")
    doc.append("- **Response Shape**:")
    doc.append("```json")
    doc.append("{")
    doc.append('  "status": "healthy",')
    doc.append('  "database": "connected",')
    doc.append('  "app": "OFC HR – Office Function Consolidator (Human Resources)",')
    doc.append('  "version": "2.0.0",')
    doc.append('  "environment": "production"')
    doc.append("}")
    doc.append("```")
    doc.append("")
    doc.append("### Readiness Probe (`GET /health/ready`)")
    doc.append("- **Path**: `GET /health/ready`")
    doc.append("- **Authentication**: Public (None)")
    doc.append("- **Behavior**: Checks PostgreSQL connectivity AND queries Ollama LLM health status. Returns `HTTP 200` if both are operational, or `HTTP 503 Service Unavailable` if either dependency is down.")
    doc.append("- **Response Shape**:")
    doc.append("```json")
    doc.append("{")
    doc.append('  "ready": true,')
    doc.append('  "database": "connected",')
    doc.append('  "llm": {')
    doc.append('    "healthy": true,')
    doc.append('    "provider": "ollama",')
    doc.append('    "model": "qwen3:30b"')
    doc.append("  }")
    doc.append("}")
    doc.append("```")
    doc.append("")

    # Section 23
    doc.append("## 23. API Documentation")
    doc.append("")
    doc.append("When enabled via `ENABLE_DOCS=true` or running in `ENVIRONMENT=development` / `local`, interactive API specifications are available at:")
    doc.append("- **Swagger UI**: [http://localhost:8000/docs](http://localhost:8000/docs)")
    doc.append("- **ReDoc Documentation**: [http://localhost:8000/redoc](http://localhost:8000/redoc)")
    doc.append("- **OpenAPI JSON**: [http://localhost:8000/openapi.json](http://localhost:8000/openapi.json)")
    doc.append("")
    doc.append("> [!TIP]")
    doc.append("> In production (`ENVIRONMENT=production` and `DEBUG=false`), `/docs`, `/redoc`, and `/openapi.json` return `HTTP 404 Not Found` with `Cache-Control: no-store` headers by default to prevent API surface discovery. Set `ENABLE_DOCS=true` only if public documentation is explicitly required.")
    doc.append("")

    # Section 24
    doc.append("## 24. Troubleshooting")
    doc.append("")
    doc.append("### 1. HTTP 401 Unauthorized")
    doc.append("- **Symptom**: `Invalid token type` or `Access token has expired`.")
    doc.append("- **Fix**: Call `/api/v1/auth/refresh-token` with the refresh token or check if the token was revoked in Redis via logout.")
    doc.append("")
    doc.append("### 2. HTTP 403 Forbidden")
    doc.append("- **Symptom**: `Access denied` or `HR Admin access required`.")
    doc.append("- **Fix**: Verify user role in JWT claims. Ensure the employee profile is in `ACTIVE` status and not `TERMINATED` or `DEACTIVATED`.")
    doc.append("")
    doc.append("### 3. HTTP 422 Unprocessable Entity")
    doc.append("- **Symptom**: Validation error listing specific fields.")
    doc.append("- **Fix**: Inspect the response `errors` array. Ensure dates use ISO format (`YYYY-MM-DD`), UUIDs are well-formed 36-character strings, and emails match valid regex.")
    doc.append("")
    doc.append("### 4. CORS Preflight Failure / Missing Access-Control-Allow-Origin")
    doc.append("- **Symptom**: Browser blocks fetch with CORS error.")
    doc.append("- **Fix**: Verify your frontend origin in `.env` (`BACKEND_CORS_ORIGINS`). Test configuration directly using `GET /api/v1/cors-debug`.")
    doc.append("")
    doc.append("### 5. Database Connection Failures (IPv6 / Supabase / Direct)")
    doc.append("- **Symptom**: Connection timed out or DNS resolution failure.")
    doc.append("- **Fix**: If using an IPv6-only cloud database provider, set `FORCE_IPV4_DB=true` in `.env`. Ensure your `DATABASE_URL` starts with `postgresql+asyncpg://`.")
    doc.append("")
    doc.append("### 6. Multiple Alembic Heads Detected")
    doc.append("- **Symptom**: `FATAL: Multiple Alembic heads detected!` during migration.")
    doc.append("- **Fix**: Run `alembic merge heads -m \"merge_heads\"` and verify with `python scripts/check_migrations.py`.")
    doc.append("")
    doc.append("### 7. Celery Worker Disconnection")
    doc.append("- **Symptom**: Celery worker logs `Error 111 connecting to localhost:6379`.")
    doc.append("- **Fix**: Verify `REDIS_URL` and `CELERY_BROKER_URL`. In local dev without Redis, set `USE_CELERY=false` to execute tasks synchronously.")
    doc.append("")

    # Section 25
    doc.append("## 25. Production Readiness Checklist")
    doc.append("")
    doc.append("| Component | Status | Verification & Codebase Evidence |")
    doc.append("| --- | --- | --- |")
    doc.append("| **Environment Variables** | Verified | Strict Pydantic `validate_production_safety` validator prevents empty secrets in production |")
    doc.append("| **Database Engine** | Verified | PostgreSQL 16 with asyncpg, connection pooling, pre-ping liveness, and connection recycling |")
    doc.append("| **Schema Migrations** | Verified | 90 Alembic migrations, single head enforcement in CI, PostgreSQL advisory locking in deploy script |")
    doc.append("| **Multi-Tenant Isolation** | Verified | Automatic `do_orm_execute` with `with_loader_criteria` on all company tables |")
    doc.append("| **Authentication** | Verified | RS256 JWT, refresh token rotation with 15s grace, Redis token blocklist, HttpOnly session cookies |")
    doc.append("| **Super Admin Security Lock** | Verified | Immutable identity enforced: only `superadmin@ofc360.com` is permitted as Super Admin |")
    doc.append("| **Role-Based Access Control** | Verified | 6 canonical roles + C-Suite mapping with strict FastAPI dependencies (`require_*`) |")
    doc.append("| **CORS Configuration** | Verified | Outermost ASGI middleware layer, credentials enabled, explicit origins list, debug endpoint |")
    doc.append("| **Security Headers** | Verified | `SecurityHeadersMiddleware` injects X-Content-Type-Options, X-Frame-Options, CSP, HSTS |")
    doc.append("| **Rate Limiting** | Verified | Global Redis sliding window (100/min) + tight limits on login (5/min), register, OTP, and AI |")
    doc.append("| **Error Handling** | Verified | Standard `APIResponse` envelope, sanitized 500 error messages, structured logging |")
    doc.append("| **Task Queues & Workers** | Verified | Celery 5.4 over Redis with graceful synchronous fallback when `USE_CELERY=false` |")
    doc.append("| **Email System** | Verified | Real SMTP with STARTTLS/SSL, template engine, exponential backoff retries, dev console fallback |")
    doc.append("| **Document Storage** | Verified | Cloudinary integration + local `/app/uploads` storage with private non-static document mounts |")
    doc.append("| **AI Runtime Isolation** | Verified | Ollama on-premise integration exclusively; external cloud LLM providers disabled in code |")
    doc.append("| **Automated Testing** | Verified | 72 automated test suites covering auth, RBAC, models, migrations, and APIs |")
    doc.append("| **Containerization** | Verified | Multi-stage Dockerfile, non-root `appuser` (UID 10001), healthchecks, docker-compose ready |")
    doc.append("")

    # Section 26
    doc.append("## 26. API ↔ Frontend Integration")
    doc.append("")
    doc.append("To connect an enterprise frontend client (React / Next.js / Vite) to this backend:")
    doc.append("")
    doc.append("### Base URLs")
    doc.append("- **Development**: `http://localhost:8000`")
    doc.append("- **Production**: `https://api.ofc360.com`")
    doc.append("")
    doc.append("### Required Request Headers")
    doc.append("```http")
    doc.append("Authorization: Bearer <jwt_access_token>")
    doc.append("Content-Type: application/json")
    doc.append("Accept: application/json")
    doc.append("```")
    doc.append("")
    doc.append("### Client Response Parsing")
    doc.append("Every response conforms to the standard envelope:")
    doc.append("```typescript")
    doc.append("interface APIResponse<T> {")
    doc.append("  success: boolean;")
    doc.append("  message: string;")
    doc.append("  data: T;")
    doc.append("  errors: Array<{ field?: string; message: string }> | null;")
    doc.append("}")
    doc.append("```")
    doc.append("")
    doc.append("### Dual-Key Compatibility")
    doc.append("Analytical and dashboard endpoints return both `snake_case` and `camelCase` keys in response bodies (e.g. `workforce_size` and `workforceSize`), eliminating the need for client-side key conversion layers.")
    doc.append("")

    # Section 27
    doc.append("## 27. Contributing")
    doc.append("")
    doc.append("1. **Branching Model**: Create feature branches from `main` (`feature/your-feature-name` or `fix/your-bug-fix`).")
    doc.append("2. **Database Modifications**:")
    doc.append("   - Never modify database tables or columns directly via SQL.")
    doc.append("   - Update SQLAlchemy models in `app/models/`.")
    doc.append("   - Autogenerate migration: `alembic revision --autogenerate -m \"describe_change\"`.")
    doc.append("   - Verify that `make db-check` passes with zero schema drift.")
    doc.append("3. **Code Quality**:")
    doc.append("   - Follow PEP 8 standards with strict type annotations.")
    doc.append("   - Run syntax verification: `python -m compileall app alembic`.")
    doc.append("4. **Testing**:")
    doc.append("   - Add unit/integration tests under `tests/` for all new endpoints.")
    doc.append("   - Run `pytest` and ensure all suites pass before opening a pull request.")
    doc.append("")

    # Section 28
    doc.append("## 28. License")
    doc.append("")
    doc.append("Proprietary and Confidential. Copyright © 2026 OFC360. All rights reserved. Unauthorized copying, reverse engineering, or redistribution is strictly prohibited.")
    doc.append("")

    # Section 29
    doc.append("## 29. Maintainers")
    doc.append("")
    doc.append("- **Engineering Team**: OFC360 Core Platform Team")
    doc.append("- **Repository Author**: vinit sharma (`sharmavinit54538@gmail.com`)")
    doc.append("- **Technical Inquiries**: `support@ofc360.com`")
    doc.append("")

    content = "\n".join(doc)
    return content

if __name__ == "__main__":
    readme_text = build_readme()
    
    # Check for forbidden terms
    if "aurix" in readme_text.lower():
        raise ValueError("CRITICAL: Forbidden term 'Aurix' found in generated README!")
        
    # Write to apiofc360/README.md
    with open("README.md", "w", encoding="utf-8") as f:
        f.write(readme_text)
    print("Successfully wrote apiofc360/README.md")
    
    # Also write to root README.md
    root_readme_path = os.path.abspath("../README.md")
    with open(root_readme_path, "w", encoding="utf-8") as f:
        f.write(readme_text)
    print(f"Successfully wrote root {root_readme_path}")
