"""Database models for the AI Email Generator Engine.

Includes generated emails subjects, bodies, recipients, and tone configurations logs.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING
import uuid

from sqlalchemy import DateTime, ForeignKey, Index, String, Text, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.company import Company


class GeneratedEmailLog(Base):
    """Log of all emails generated by AI for company workflows."""

    __tablename__ = "generated_email_logs"
    __table_args__ = (
        Index("ix_generated_emails_company_id", "company_id"),
        Index("ix_generated_emails_type", "email_type"),
    )

    id: Mapped[uuid.UUID] = mapped_column(PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    company_id: Mapped[uuid.UUID] = mapped_column(PG_UUID(as_uuid=True), ForeignKey("companies.id", ondelete="CASCADE"), nullable=False)

    recipient_email: Mapped[str] = mapped_column(String(255), nullable=False)
    email_type: Mapped[str] = mapped_column(String(50), nullable=False)  # OFFER_LETTER, REJECTION, PROMOTION, LEAVE_APPROVAL, LEAVE_REJECTION, WARNING_LETTER, HR_ANNOUNCEMENT, BIRTHDAY_WISHES, ANNIVERSARY_WISHES, MEETING_INVITE, REMINDER_EMAIL, PERFORMANCE_FEEDBACK
    tone: Mapped[str] = mapped_column(String(20), nullable=False, default="PROFESSIONAL")  # PROFESSIONAL, FRIENDLY, FORMAL, CORPORATE
    
    subject: Mapped[str] = mapped_column(String(255), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())

    # Relations
    company: Mapped[Company] = relationship("Company", lazy="select")
